# coding: utf-8

# flake8: noqa

"""
    NinjaOne Public API 2.0

    Ninja One Public API documentation. <br><br> See also: <br>  <a href=\"https://resources.ninjarmm.com/API/Ninja+RMM+Public+API+v2.0.5+Device+Filter+Syntax.pdf\">Device Filter syntax</a><br> <a href=\"https://resources.ninjarmm.com/API/Ninja+RMM+Public+API+v2.0.5+Webhooks.pdf\">Webhooks</a>

    The version of the OpenAPI document: 2.0.9-draft
    Contact: api@ninjarmm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AssetTagsApi",
    "BackupApi",
    "ChecklistTemplatesApi",
    "CustomFieldsApi",
    "DocumentTemplatesApi",
    "KnowledgeBaseArticlesApi",
    "LocationApi",
    "OrganizationChecklistsApi",
    "OrganizationDocumentsApi",
    "RelatedItemsApi",
    "VulnerabilityManagementApi",
    "DevicesApi",
    "GroupsApi",
    "ManagementApi",
    "OrganizationApi",
    "QueriesApi",
    "SystemApi",
    "TicketingApi",
    "WebhooksApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ActivitiesResponse",
    "Activity",
    "AgentDevice",
    "AgentDeviceAllOfMemory",
    "AgentDeviceAllOfOs",
    "AgentDeviceAllOfSystem",
    "AgreementDTO",
    "Alert",
    "AntivirusStatusReport",
    "AntivirusThreatsReport",
    "AppUserAndContactPublicApiDTO",
    "Application",
    "ArchiveChecklistTemplate200ResponseInner",
    "ArchiveChecklistTemplate200ResponseInnerDescription",
    "ArchiveChecklistTemplate200ResponseInnerLastUpdatedBy",
    "ArchiveChecklistTemplate200ResponseInnerTasksInner",
    "ArchiveChecklistTemplateRequest",
    "ArchiveChecklistTemplatesRequest",
    "ArchiveClientChecklistRequest",
    "ArchiveClientDocument200Response",
    "ArchiveClientDocument200ResponseFieldsInner",
    "ArchiveOrganizationChecklists200ResponseInner",
    "ArchiveOrganizationChecklists200ResponseInnerTasksInner",
    "ArchiveOrganizationChecklistsRequest",
    "ArchiveUserInfo",
    "AttachmentMetadata",
    "AttachmentMetadataPublicApiDTO",
    "AttributeContent",
    "AttributeContentAdvancedSettings",
    "AttributeContentAdvancedSettingsComplexityRules",
    "AttributeContentAdvancedSettingsDateFilters",
    "AttributeContentAdvancedSettingsNumericRange",
    "AttributeContentValue",
    "AttributeData",
    "AttributePublicApiDTO",
    "AttributeValueDTO",
    "AttributeValueUpdatedByInfo",
    "AutomationScript",
    "BackupJob",
    "BackupJobReport",
    "BackupUsage",
    "BatchUpdateTagsRequest",
    "BodyPart",
    "CarbonCopy",
    "CcList",
    "ChecklistDescription",
    "ChecklistTemplatePublicApiDTO",
    "ChecklistTemplateTaskPublicApiDTO",
    "ChecklistTemplateTaskPublicApiRequest",
    "ChecklistUserResponseDTO",
    "ClientChecklistPublicApiDTO",
    "ClientChecklistTaskPublicApiDTO",
    "ClientChecklistTaskPublicApiRequest",
    "ClientDocumentAttributeWithValuePublicApiDTO",
    "ClientDocumentWithAttributeValuesBulkCreatePublicApiRequest",
    "ClientDocumentWithAttributeValuesBulkUpdatePublicApiRequest",
    "ClientDocumentWithAttributeValuesPublicApiDTO",
    "ClientDocumentWithAttributeValuesPublicApiRequest",
    "ClientDocumentWithUpdatedAttributeValuesPublicApiDTO",
    "CloudMonitorDNS",
    "CloudMonitorEmailServer",
    "CloudMonitorHTTP",
    "CloudMonitorPing",
    "CloudMonitorPortScan",
    "ComputerSystem",
    "ComputerSystemsReport",
    "Condition",
    "ConfigureWebhookRequest",
    "ConfigureWebhookRequestHeadersInner",
    "ContactResponseDTO",
    "ContentDisposition",
    "ControlWindowsServiceRequest",
    "CreateChecklistTemplatePublicApiRequest",
    "CreateChecklistTemplatesRequestInner",
    "CreateClientChecklistAndTasksPublicApiRequest",
    "CreateCustomFieldsPolicyConditionRequest",
    "CreateDefaultResponse",
    "CreateDefaultResponseAttributeValuesInner",
    "CreateDefaultResponseCcList",
    "CreateDefaultResponseStatus",
    "CreateDocumentTemplateRequest",
    "CreateDocumentTemplateRequestFieldsInner",
    "CreateDocumentTemplateRequestFieldsInnerFieldContent",
    "CreateDocumentTemplateRequestFieldsInnerFieldContentValuesInner",
    "CreateItamTagRequest",
    "CreateKnowledgeBaseArticles200ResponseInner",
    "CreateKnowledgeBaseArticles200ResponseInnerAttachmentsInner",
    "CreateKnowledgeBaseArticles200ResponseInnerAttachmentsInnerMetadata",
    "CreateKnowledgeBaseArticlesRequestInner",
    "CreateKnowledgeBaseArticlesRequestInnerContent",
    "CreateOrganizationChecklistsRequestInner",
    "CreateOrganizationDefaultResponse",
    "CreateOrganizationDefaultResponseLocationsInner",
    "CreateOrganizationDefaultResponseSettings",
    "CreateOrganizationDefaultResponseSettingsTrayicon",
    "CreateOrganizationDocumentRequest",
    "CreateOrganizationDocumentsRequestInner",
    "CreateOrganizationRequest",
    "CreateOrganizationRequestLocationsInner",
    "CreateOrganizationRequestPoliciesInner",
    "CreatePolicyRequest",
    "CreateRelatedItem200Response",
    "CreateRelatedItemForEntityRequest",
    "CreateRequest",
    "CreateRequestAttributesInner",
    "CreateRequestCc",
    "CreateRequestDescription",
    "CreateSecureRelatedItemForEntityRequest",
    "CreateTag200Response",
    "CreateTagRequest",
    "CreateWindowsEventPolicyConditionRequest",
    "CredentialReference",
    "Cursor",
    "CustomFieldPolicyConditionResponse",
    "CustomFieldsPolicyConditionCreateRequest",
    "Device",
    "DeviceAntivirusStatus",
    "DeviceAntivirusThreat",
    "DeviceApplication",
    "DeviceComputerSystem",
    "DeviceCredentialOptions",
    "DeviceDiskDrive",
    "DeviceHealthReport",
    "DeviceHealthSummary",
    "DeviceIDList",
    "DeviceLink",
    "DeviceLoggedOnUser",
    "DeviceMutableProperties",
    "DeviceNetworkInterfaces",
    "DeviceOSPatch",
    "DeviceOperatingSystem",
    "DevicePolicyOverrides",
    "DeviceProcessor",
    "DeviceRAIDController",
    "DeviceRAIDDrive",
    "DeviceScriptingOptions",
    "DeviceSearchMatch",
    "DeviceSearchResults",
    "DeviceSoftwarePatch",
    "DeviceUsageReport",
    "DeviceVolume",
    "DeviceWindowsService",
    "DiskDrive",
    "DiskDriveReport",
    "DocumentAttributeContentPublicApi",
    "DocumentAttributeContentValuePublicApi",
    "DocumentItemPublicApiDTO",
    "DocumentTemplatePublicApiDTO",
    "EndUserCustomization",
    "FeatureSettings",
    "FetchAllScanGroups200ResponseInner",
    "FormDataBodyPart",
    "FormDataContentDisposition",
    "GenerateInstallerRequestDto",
    "GetActivitiesDefaultResponse",
    "GetAllUserAndContacts200ResponseInner",
    "GetAntivirusStatusReportDefaultResponse",
    "GetAntivirusStatusReportDefaultResponseResultsInner",
    "GetAntivirusThreatsDefaultResponse",
    "GetAntivirusThreatsDefaultResponseResultsInner",
    "GetAutomationScriptsDefaultResponseInner",
    "GetAutomationScriptsDefaultResponseInnerScriptVariablesInner",
    "GetBoardsDefaultResponseInner",
    "GetBoardsDefaultResponseInnerConditions",
    "GetBoardsDefaultResponseInnerConditionsAnyInner",
    "GetComputerSystemsDefaultResponse",
    "GetComputerSystemsDefaultResponseResultsInner",
    "GetContactsDefaultResponseInner",
    "GetCustomFieldsDetailedReportDefaultResponse",
    "GetCustomFieldsDetailedReportDefaultResponseResultsInner",
    "GetCustomFieldsDetailedReportDefaultResponseResultsInnerFieldsInner",
    "GetCustomFieldsDetailedReportDefaultResponseResultsInnerFieldsInnerUpdatedBy",
    "GetCustomFieldsPolicyConditionsDefaultResponseInner",
    "GetCustomFieldsPolicyConditionsDefaultResponseInnerInheritance",
    "GetCustomFieldsPolicyConditionsDefaultResponseInnerMatchAllInner",
    "GetCustomFieldsPolicyConditionsDefaultResponseInnerScriptsInner",
    "GetCustomFieldsPolicyConditionsDefaultResponseInnerScriptsInnerScriptVariablesInner",
    "GetCustomFieldsReportDefaultResponse",
    "GetCustomFieldsReportDefaultResponseResultsInner",
    "GetDevice200Response",
    "GetDevice200ResponseMaintenance",
    "GetDevice200ResponseNotesInner",
    "GetDevice200ResponseReferences",
    "GetDevice200ResponseReferencesBackupUsage",
    "GetDevice200ResponseReferencesRole",
    "GetDevice200ResponseReferencesRolePolicy",
    "GetDevice200ResponseReferencesWarranty",
    "GetDeviceActiveJobsDefaultResponseInner",
    "GetDeviceActiveJobsDefaultResponseInnerDevice",
    "GetDeviceActivitiesDefaultResponse",
    "GetDeviceActivitiesDefaultResponseActivitiesInner",
    "GetDeviceAlertsDefaultResponseInner",
    "GetDeviceDiskDrivesDefaultResponseInner",
    "GetDeviceGlobalCustomFieldsDefaultResponseInner",
    "GetDeviceGlobalCustomFieldsDefaultResponseInnerContent",
    "GetDeviceGlobalCustomFieldsDefaultResponseInnerContentEndUserCustomization",
    "GetDeviceGlobalCustomFieldsDefaultResponseInnerContentValuesInner",
    "GetDeviceHealthReportDefaultResponse",
    "GetDeviceHealthReportDefaultResponseResultsInner",
    "GetDeviceInstalledOSPatchesDefaultResponseInner",
    "GetDeviceInstalledSoftwarePatchesDefaultResponseInner",
    "GetDeviceLastLoggedOnUserDefaultResponse",
    "GetDeviceLinkDefaultResponse",
    "GetDeviceNetworkInterfacesDefaultResponseInner",
    "GetDeviceProcessorsDefaultResponseInner",
    "GetDeviceServicesDefaultResponseInner",
    "GetDeviceSoftwareDefaultResponseInner",
    "GetDeviceUsage200Response",
    "GetDeviceVolumesDefaultResponseInner",
    "GetDeviceVolumesDefaultResponseInnerBitLockerStatus",
    "GetDiskDrivesDefaultResponse",
    "GetDiskDrivesDefaultResponseResultsInner",
    "GetDocumentTemplatesWithAttributes200ResponseInner",
    "GetDocumentTemplatesWithAttributes200ResponseInnerArchivedBy",
    "GetDocumentTemplatesWithAttributes200ResponseInnerFieldsInner",
    "GetDocumentTemplatesWithAttributes200ResponseInnerFieldsInnerFieldContent",
    "GetDocumentTemplatesWithAttributes200ResponseInnerFieldsInnerFieldContentAdvancedSettings",
    "GetDocumentTemplatesWithAttributes200ResponseInnerFieldsInnerFieldContentAdvancedSettingsComplexityRules",
    "GetDocumentTemplatesWithAttributes200ResponseInnerFieldsInnerFieldContentAdvancedSettingsDateFilters",
    "GetDocumentTemplatesWithAttributes200ResponseInnerFieldsInnerFieldContentAdvancedSettingsNumericRange",
    "GetDocumentTemplatesWithAttributes200ResponseInnerFieldsInnerFieldContentValuesInner",
    "GetEnabledNotificationChannelsDefaultResponseInner",
    "GetEndUsersDefaultResponseInner",
    "GetGroupsDefaultResponseInner",
    "GetInstalledOSPatchesDefaultResponse",
    "GetInstalledOSPatchesDefaultResponseResultsInner",
    "GetInstalledSoftwarePatchesDefaultResponse",
    "GetInstalledSoftwarePatchesDefaultResponseResultsInner",
    "GetInstallerDefaultResponse",
    "GetInstallerRequest",
    "GetInstallerRequestContent",
    "GetIntegrityCheckJobs200Response",
    "GetIntegrityCheckJobs200ResponseCursor",
    "GetIntegrityCheckJobs200ResponseResultsInner",
    "GetItamTagsPublicApiResponse",
    "GetItamTagsResponse",
    "GetKnowledgeBaseFolderContent200Response",
    "GetKnowledgeBaseFolderContent200ResponseContentInner",
    "GetLastLoggedOnUsersReportDefaultResponse",
    "GetLastLoggedOnUsersReportDefaultResponseResultsInner",
    "GetLocationUsage200Response",
    "GetLocationsDefaultResponseInner",
    "GetNetworkInterfacesDefaultResponse",
    "GetNetworkInterfacesDefaultResponseResultsInner",
    "GetOperatingSystemsDefaultResponse",
    "GetOperatingSystemsDefaultResponseResultsInner",
    "GetOrganizationsDefaultResponseInner",
    "GetPolicyOverrides1DefaultResponse",
    "GetPolicyOverrides1DefaultResponseResultsInner",
    "GetPolicyOverridesDefaultResponse",
    "GetProcessorsDefaultResponse",
    "GetProcessorsDefaultResponseResultsInner",
    "GetRAIDControllerReportDefaultResponse",
    "GetRAIDControllerReportDefaultResponseResultsInner",
    "GetRAIDDriveReportDefaultResponse",
    "GetRAIDDriveReportDefaultResponseResultsInner",
    "GetScheduledTasksDefaultResponseInner",
    "GetScopedCustomFieldsDetailedReportDefaultResponse",
    "GetScopedCustomFieldsDetailedReportDefaultResponseResultsInner",
    "GetScopedCustomFieldsReportDefaultResponse",
    "GetScopedCustomFieldsReportDefaultResponseResultsInner",
    "GetSoftwareDefaultResponse",
    "GetSoftwareDefaultResponseResultsInner",
    "GetSoftwareProductsDefaultResponseInner",
    "GetTags200Response",
    "GetTags200ResponseTagsInner",
    "GetTags200ResponseTagsInnerCreatedBy",
    "GetTicketAttributesDefaultResponseInner",
    "GetTicketFormByIdDefaultResponse",
    "GetTicketFormByIdDefaultResponseContent",
    "GetTicketFormByIdDefaultResponseContentTimerSettings",
    "GetTicketLogEntriesByTicketIdDefaultResponseInner",
    "GetTicketLogEntriesByTicketIdDefaultResponseInnerAutomation",
    "GetTicketLogEntriesByTicketIdDefaultResponseInnerTechniciansTaggedMetadataInner",
    "GetTicketLogEntriesByTicketIdDefaultResponseInnerTicketTimeEntry",
    "GetTicketLogEntriesByTicketIdDefaultResponseInnerTicketTimeEntryAgreement",
    "GetTicketsByBoardDefaultResponse",
    "GetTicketsByBoardDefaultResponseMetadata",
    "GetTicketsByBoardDefaultResponseMetadataAttributesValue",
    "GetTicketsByBoardRequest",
    "GetTicketsByBoardRequestSortByInner",
    "GetVolumesDefaultResponse",
    "GetVolumesDefaultResponseResultsInner",
    "GetWindowsEventPolicyConditionsDefaultResponseInner",
    "GetWindowsEventPolicyConditionsDefaultResponseInnerOccurrence",
    "GetWindowsEventPolicyConditionsDefaultResponseInnerText",
    "GetWindowsServicesReportDefaultResponse",
    "GetWindowsServicesReportDefaultResponseResultsInner",
    "Group",
    "HTTPHeader",
    "InstallerContent",
    "ItamManageAssetRequestPublicApiDTO",
    "ItamSetAssetTagsRequestPublicApiDTO",
    "ItamTagDTO",
    "ItamTagPublicApiDTO",
    "Job",
    "KnowledgeBaseArticleBulkCreatePublicApiRequest",
    "KnowledgeBaseArticleBulkUpdatePublicApiRequest",
    "KnowledgeBaseArticlePublicApiContent",
    "KnowledgeBaseArticlePublicApiDTO",
    "KnowledgeBaseAttachmentPublicApiDTO",
    "KnowledgeBaseFolderItemPublicApiDTO",
    "KnowledgeBaseFolderPublicApiDTO",
    "Link",
    "Location",
    "LocationBackupUsageSummary",
    "LocationModel",
    "LocationWithOrganizationRef",
    "LockhartIntegrityCheckJob",
    "LockhartIntegrityCheckJobCreationRequest",
    "LockhartIntegrityCheckJobCreationResponse",
    "LockhartIntegrityCheckJobReport",
    "LockhartIntegrityCheckJobReportResultsInner",
    "LoggedOnUser",
    "LoggedOnUsersReport",
    "Maintenance",
    "MaintenanceSettings",
    "MdmDevice",
    "Memory",
    "MergeItamTagsPublicApiRequest",
    "MergeTagsRequest",
    "MovePublicApiRequest",
    "MoveRequest",
    "MultiPart",
    "NMSServer",
    "NMSTarget",
    "NetworkInterface",
    "NetworkInterfacesReport",
    "NewDocumentAttributeContentPublicApi",
    "NewDocumentAttributeContentValuePublicApi",
    "NewDocumentItemPublicApiRequest",
    "NewDocumentTemplatePublicApiRequest",
    "NewRelatedItemEntityRequest",
    "NewRelatedItemSecureValueRequest",
    "NewTicket",
    "NewTicketLogEntry",
    "NodeActivitiesResponse",
    "NodeApprovalOperationRequest",
    "NodeAttributeInfo",
    "NodeAttributes",
    "NodeAttributesDetailed",
    "NodeAttributesDetailedReport",
    "NodeAttributesReport",
    "NodeReferences",
    "NodeRole",
    "NodeRolePolicyAssignment",
    "NodeWithDetailedReferences",
    "Note",
    "NotificationChannel",
    "OSPatch",
    "OSPatchReport",
    "OperatingSystem",
    "OperatingSystemsReport",
    "Organization",
    "OrganizationDetailed",
    "OrganizationModel",
    "OrganizationSettings",
    "OrganizationWithLocationsAndPolicyAssignmentsModel",
    "ParameterizedHeader",
    "Policy",
    "PolicyConditionCustomField",
    "PolicyConditionInheritanceStatus",
    "PolicyConditionScript",
    "PolicyConditionScriptVariable",
    "PolicyInfo",
    "PolicyOverrides",
    "PolicyOverridesReport",
    "Processor",
    "ProcessorReport",
    "PromoteClientChecklistWithNamePublicApiRequest",
    "PromoteClientChecklistsRequestInner",
    "PublicScanGroup",
    "RAIDControllerReport",
    "RAIDDriveReport",
    "RebootDevicesRequest",
    "RebootRequest",
    "RelatedItemPublicApiDTO",
    "RequestScriptingOptionsDefaultResponse",
    "RequestScriptingOptionsDefaultResponseCategoriesInner",
    "RequestScriptingOptionsDefaultResponseCredentials",
    "RequestScriptingOptionsDefaultResponseCredentialsCredentialsInner",
    "RequestScriptingOptionsDefaultResponseScriptsInner",
    "RestoreChecklistTemplatesRequest",
    "Rule",
    "RunScriptOnDeviceRequest",
    "RunScriptRequest",
    "ScheduledTask",
    "ScopedAttributes",
    "ScopedAttributesDetailed",
    "ScopedAttributesDetailedReport",
    "ScopedAttributesReport",
    "Script",
    "ScriptCategory",
    "ScriptVariable",
    "SearchDefaultResponse",
    "SearchDefaultResponseDevicesInner",
    "SetTagsForAssetRequest",
    "SetWindowsServiceConfigurationRequest",
    "SoftwarePatch",
    "SoftwarePatchReport",
    "SoftwareProduct",
    "SoftwareReport",
    "SortBy",
    "SubmitIntegrityCheckJob200Response",
    "SubmitIntegrityCheckJobRequest",
    "TechniciansTaggedMetadataDTO",
    "TicketBoardScrollingRequestDTO",
    "TicketDTO",
    "TicketDashboardPublicApiDTO",
    "TicketFormContent",
    "TicketFormPublicApiDTO",
    "TicketLogEntryAutomationDTO",
    "TicketLogEntryPublicApiDTO",
    "TicketMetadata",
    "TicketStatusPublicApiDTO",
    "TicketTimeEntryDTO",
    "TicketingAttributePublicApiDTO",
    "TicketingAttributeValue",
    "TicketingBoardPublicApiDTO",
    "TimerSettings",
    "UpdateChecklistTemplatePublicApiRequest",
    "UpdateChecklistTemplatesRequestInner",
    "UpdateChecklistTemplatesRequestInnerTasksInner",
    "UpdateClientChecklistAndTasksPublicApiRequest",
    "UpdateDeviceMaintenanceRequest",
    "UpdateDeviceRequest",
    "UpdateDocumentItemPublicApiRequest",
    "UpdateDocumentTemplatePublicApiRequest",
    "UpdateDocumentTemplateRequest",
    "UpdateDocumentTemplateRequestFieldsInner",
    "UpdateItamTagRequest",
    "UpdateKnowledgeBaseArticlesRequestInner",
    "UpdateOrganizationChecklistsRequestInner",
    "UpdateOrganizationChecklistsRequestInnerTasksInner",
    "UpdateOrganizationDocuments200ResponseInner",
    "UpdateOrganizationDocumentsRequestInner",
    "UpdateOrganizationRequest",
    "UpdateRequest",
    "UpdateTagRequest",
    "UpdateTicket",
    "UploadTempAttachments200ResponseInner",
    "UploadTempAttachmentsRequestFilesInner",
    "UploadTempAttachmentsRequestFilesInnerContentDisposition",
    "UploadTempAttachmentsRequestFilesInnerFormDataContentDisposition",
    "UploadTempAttachmentsRequestFilesInnerMediaType",
    "UploadTempAttachmentsRequestFilesInnerParent",
    "UploadTempAttachmentsRequestFilesInnerParentParameterizedHeadersValueInner",
    "User",
    "UserBasicInfo",
    "VMGuest",
    "VMHost",
    "Volume",
    "VolumeBitLockerStatus",
    "VolumesReport",
    "WarrantyDates",
    "WebhookConfiguration",
    "WindowsEventPolicyConditionCreateRequest",
    "WindowsEventPolicyConditionOccurrence",
    "WindowsEventPolicyConditionResponse",
    "WindowsEventPolicyConditionText",
    "WindowsService",
    "WindowsServiceConfiguration",
    "WindowsServiceControlRequest",
    "WindowsServiceReport",
]

# import apis into sdk package
from tl_ninjarmm.api.asset_tags_api import AssetTagsApi as AssetTagsApi
from tl_ninjarmm.api.backup_api import BackupApi as BackupApi
from tl_ninjarmm.api.checklist_templates_api import ChecklistTemplatesApi as ChecklistTemplatesApi
from tl_ninjarmm.api.custom_fields_api import CustomFieldsApi as CustomFieldsApi
from tl_ninjarmm.api.document_templates_api import DocumentTemplatesApi as DocumentTemplatesApi
from tl_ninjarmm.api.knowledge_base_articles_api import KnowledgeBaseArticlesApi as KnowledgeBaseArticlesApi
from tl_ninjarmm.api.location_api import LocationApi as LocationApi
from tl_ninjarmm.api.organization_checklists_api import OrganizationChecklistsApi as OrganizationChecklistsApi
from tl_ninjarmm.api.organization_documents_api import OrganizationDocumentsApi as OrganizationDocumentsApi
from tl_ninjarmm.api.related_items_api import RelatedItemsApi as RelatedItemsApi
from tl_ninjarmm.api.vulnerability_management_api import VulnerabilityManagementApi as VulnerabilityManagementApi
from tl_ninjarmm.api.devices_api import DevicesApi as DevicesApi
from tl_ninjarmm.api.groups_api import GroupsApi as GroupsApi
from tl_ninjarmm.api.management_api import ManagementApi as ManagementApi
from tl_ninjarmm.api.organization_api import OrganizationApi as OrganizationApi
from tl_ninjarmm.api.queries_api import QueriesApi as QueriesApi
from tl_ninjarmm.api.system_api import SystemApi as SystemApi
from tl_ninjarmm.api.ticketing_api import TicketingApi as TicketingApi
from tl_ninjarmm.api.webhooks_api import WebhooksApi as WebhooksApi

# import ApiClient
from tl_ninjarmm.api_response import ApiResponse as ApiResponse
from tl_ninjarmm.api_client import ApiClient as ApiClient
from tl_ninjarmm.configuration import Configuration as Configuration
from tl_ninjarmm.exceptions import OpenApiException as OpenApiException
from tl_ninjarmm.exceptions import ApiTypeError as ApiTypeError
from tl_ninjarmm.exceptions import ApiValueError as ApiValueError
from tl_ninjarmm.exceptions import ApiKeyError as ApiKeyError
from tl_ninjarmm.exceptions import ApiAttributeError as ApiAttributeError
from tl_ninjarmm.exceptions import ApiException as ApiException

# import models into sdk package
from tl_ninjarmm.models.activities_response import ActivitiesResponse as ActivitiesResponse
from tl_ninjarmm.models.activity import Activity as Activity
from tl_ninjarmm.models.agent_device import AgentDevice as AgentDevice
from tl_ninjarmm.models.agent_device_all_of_memory import AgentDeviceAllOfMemory as AgentDeviceAllOfMemory
from tl_ninjarmm.models.agent_device_all_of_os import AgentDeviceAllOfOs as AgentDeviceAllOfOs
from tl_ninjarmm.models.agent_device_all_of_system import AgentDeviceAllOfSystem as AgentDeviceAllOfSystem
from tl_ninjarmm.models.agreement_dto import AgreementDTO as AgreementDTO
from tl_ninjarmm.models.alert import Alert as Alert
from tl_ninjarmm.models.antivirus_status_report import AntivirusStatusReport as AntivirusStatusReport
from tl_ninjarmm.models.antivirus_threats_report import AntivirusThreatsReport as AntivirusThreatsReport
from tl_ninjarmm.models.app_user_and_contact_public_api_dto import AppUserAndContactPublicApiDTO as AppUserAndContactPublicApiDTO
from tl_ninjarmm.models.application import Application as Application
from tl_ninjarmm.models.archive_checklist_template200_response_inner import ArchiveChecklistTemplate200ResponseInner as ArchiveChecklistTemplate200ResponseInner
from tl_ninjarmm.models.archive_checklist_template200_response_inner_description import ArchiveChecklistTemplate200ResponseInnerDescription as ArchiveChecklistTemplate200ResponseInnerDescription
from tl_ninjarmm.models.archive_checklist_template200_response_inner_last_updated_by import ArchiveChecklistTemplate200ResponseInnerLastUpdatedBy as ArchiveChecklistTemplate200ResponseInnerLastUpdatedBy
from tl_ninjarmm.models.archive_checklist_template200_response_inner_tasks_inner import ArchiveChecklistTemplate200ResponseInnerTasksInner as ArchiveChecklistTemplate200ResponseInnerTasksInner
from tl_ninjarmm.models.archive_checklist_template_request import ArchiveChecklistTemplateRequest as ArchiveChecklistTemplateRequest
from tl_ninjarmm.models.archive_checklist_templates_request import ArchiveChecklistTemplatesRequest as ArchiveChecklistTemplatesRequest
from tl_ninjarmm.models.archive_client_checklist_request import ArchiveClientChecklistRequest as ArchiveClientChecklistRequest
from tl_ninjarmm.models.archive_client_document200_response import ArchiveClientDocument200Response as ArchiveClientDocument200Response
from tl_ninjarmm.models.archive_client_document200_response_fields_inner import ArchiveClientDocument200ResponseFieldsInner as ArchiveClientDocument200ResponseFieldsInner
from tl_ninjarmm.models.archive_organization_checklists200_response_inner import ArchiveOrganizationChecklists200ResponseInner as ArchiveOrganizationChecklists200ResponseInner
from tl_ninjarmm.models.archive_organization_checklists200_response_inner_tasks_inner import ArchiveOrganizationChecklists200ResponseInnerTasksInner as ArchiveOrganizationChecklists200ResponseInnerTasksInner
from tl_ninjarmm.models.archive_organization_checklists_request import ArchiveOrganizationChecklistsRequest as ArchiveOrganizationChecklistsRequest
from tl_ninjarmm.models.archive_user_info import ArchiveUserInfo as ArchiveUserInfo
from tl_ninjarmm.models.attachment_metadata import AttachmentMetadata as AttachmentMetadata
from tl_ninjarmm.models.attachment_metadata_public_api_dto import AttachmentMetadataPublicApiDTO as AttachmentMetadataPublicApiDTO
from tl_ninjarmm.models.attribute_content import AttributeContent as AttributeContent
from tl_ninjarmm.models.attribute_content_advanced_settings import AttributeContentAdvancedSettings as AttributeContentAdvancedSettings
from tl_ninjarmm.models.attribute_content_advanced_settings_complexity_rules import AttributeContentAdvancedSettingsComplexityRules as AttributeContentAdvancedSettingsComplexityRules
from tl_ninjarmm.models.attribute_content_advanced_settings_date_filters import AttributeContentAdvancedSettingsDateFilters as AttributeContentAdvancedSettingsDateFilters
from tl_ninjarmm.models.attribute_content_advanced_settings_numeric_range import AttributeContentAdvancedSettingsNumericRange as AttributeContentAdvancedSettingsNumericRange
from tl_ninjarmm.models.attribute_content_value import AttributeContentValue as AttributeContentValue
from tl_ninjarmm.models.attribute_data import AttributeData as AttributeData
from tl_ninjarmm.models.attribute_public_api_dto import AttributePublicApiDTO as AttributePublicApiDTO
from tl_ninjarmm.models.attribute_value_dto import AttributeValueDTO as AttributeValueDTO
from tl_ninjarmm.models.attribute_value_updated_by_info import AttributeValueUpdatedByInfo as AttributeValueUpdatedByInfo
from tl_ninjarmm.models.automation_script import AutomationScript as AutomationScript
from tl_ninjarmm.models.backup_job import BackupJob as BackupJob
from tl_ninjarmm.models.backup_job_report import BackupJobReport as BackupJobReport
from tl_ninjarmm.models.backup_usage import BackupUsage as BackupUsage
from tl_ninjarmm.models.batch_update_tags_request import BatchUpdateTagsRequest as BatchUpdateTagsRequest
from tl_ninjarmm.models.body_part import BodyPart as BodyPart
from tl_ninjarmm.models.carbon_copy import CarbonCopy as CarbonCopy
from tl_ninjarmm.models.cc_list import CcList as CcList
from tl_ninjarmm.models.checklist_description import ChecklistDescription as ChecklistDescription
from tl_ninjarmm.models.checklist_template_public_api_dto import ChecklistTemplatePublicApiDTO as ChecklistTemplatePublicApiDTO
from tl_ninjarmm.models.checklist_template_task_public_api_dto import ChecklistTemplateTaskPublicApiDTO as ChecklistTemplateTaskPublicApiDTO
from tl_ninjarmm.models.checklist_template_task_public_api_request import ChecklistTemplateTaskPublicApiRequest as ChecklistTemplateTaskPublicApiRequest
from tl_ninjarmm.models.checklist_user_response_dto import ChecklistUserResponseDTO as ChecklistUserResponseDTO
from tl_ninjarmm.models.client_checklist_public_api_dto import ClientChecklistPublicApiDTO as ClientChecklistPublicApiDTO
from tl_ninjarmm.models.client_checklist_task_public_api_dto import ClientChecklistTaskPublicApiDTO as ClientChecklistTaskPublicApiDTO
from tl_ninjarmm.models.client_checklist_task_public_api_request import ClientChecklistTaskPublicApiRequest as ClientChecklistTaskPublicApiRequest
from tl_ninjarmm.models.client_document_attribute_with_value_public_api_dto import ClientDocumentAttributeWithValuePublicApiDTO as ClientDocumentAttributeWithValuePublicApiDTO
from tl_ninjarmm.models.client_document_with_attribute_values_bulk_create_public_api_request import ClientDocumentWithAttributeValuesBulkCreatePublicApiRequest as ClientDocumentWithAttributeValuesBulkCreatePublicApiRequest
from tl_ninjarmm.models.client_document_with_attribute_values_bulk_update_public_api_request import ClientDocumentWithAttributeValuesBulkUpdatePublicApiRequest as ClientDocumentWithAttributeValuesBulkUpdatePublicApiRequest
from tl_ninjarmm.models.client_document_with_attribute_values_public_api_dto import ClientDocumentWithAttributeValuesPublicApiDTO as ClientDocumentWithAttributeValuesPublicApiDTO
from tl_ninjarmm.models.client_document_with_attribute_values_public_api_request import ClientDocumentWithAttributeValuesPublicApiRequest as ClientDocumentWithAttributeValuesPublicApiRequest
from tl_ninjarmm.models.client_document_with_updated_attribute_values_public_api_dto import ClientDocumentWithUpdatedAttributeValuesPublicApiDTO as ClientDocumentWithUpdatedAttributeValuesPublicApiDTO
from tl_ninjarmm.models.cloud_monitor_dns import CloudMonitorDNS as CloudMonitorDNS
from tl_ninjarmm.models.cloud_monitor_email_server import CloudMonitorEmailServer as CloudMonitorEmailServer
from tl_ninjarmm.models.cloud_monitor_http import CloudMonitorHTTP as CloudMonitorHTTP
from tl_ninjarmm.models.cloud_monitor_ping import CloudMonitorPing as CloudMonitorPing
from tl_ninjarmm.models.cloud_monitor_port_scan import CloudMonitorPortScan as CloudMonitorPortScan
from tl_ninjarmm.models.computer_system import ComputerSystem as ComputerSystem
from tl_ninjarmm.models.computer_systems_report import ComputerSystemsReport as ComputerSystemsReport
from tl_ninjarmm.models.condition import Condition as Condition
from tl_ninjarmm.models.configure_webhook_request import ConfigureWebhookRequest as ConfigureWebhookRequest
from tl_ninjarmm.models.configure_webhook_request_headers_inner import ConfigureWebhookRequestHeadersInner as ConfigureWebhookRequestHeadersInner
from tl_ninjarmm.models.contact_response_dto import ContactResponseDTO as ContactResponseDTO
from tl_ninjarmm.models.content_disposition import ContentDisposition as ContentDisposition
from tl_ninjarmm.models.control_windows_service_request import ControlWindowsServiceRequest as ControlWindowsServiceRequest
from tl_ninjarmm.models.create_checklist_template_public_api_request import CreateChecklistTemplatePublicApiRequest as CreateChecklistTemplatePublicApiRequest
from tl_ninjarmm.models.create_checklist_templates_request_inner import CreateChecklistTemplatesRequestInner as CreateChecklistTemplatesRequestInner
from tl_ninjarmm.models.create_client_checklist_and_tasks_public_api_request import CreateClientChecklistAndTasksPublicApiRequest as CreateClientChecklistAndTasksPublicApiRequest
from tl_ninjarmm.models.create_custom_fields_policy_condition_request import CreateCustomFieldsPolicyConditionRequest as CreateCustomFieldsPolicyConditionRequest
from tl_ninjarmm.models.create_default_response import CreateDefaultResponse as CreateDefaultResponse
from tl_ninjarmm.models.create_default_response_attribute_values_inner import CreateDefaultResponseAttributeValuesInner as CreateDefaultResponseAttributeValuesInner
from tl_ninjarmm.models.create_default_response_cc_list import CreateDefaultResponseCcList as CreateDefaultResponseCcList
from tl_ninjarmm.models.create_default_response_status import CreateDefaultResponseStatus as CreateDefaultResponseStatus
from tl_ninjarmm.models.create_document_template_request import CreateDocumentTemplateRequest as CreateDocumentTemplateRequest
from tl_ninjarmm.models.create_document_template_request_fields_inner import CreateDocumentTemplateRequestFieldsInner as CreateDocumentTemplateRequestFieldsInner
from tl_ninjarmm.models.create_document_template_request_fields_inner_field_content import CreateDocumentTemplateRequestFieldsInnerFieldContent as CreateDocumentTemplateRequestFieldsInnerFieldContent
from tl_ninjarmm.models.create_document_template_request_fields_inner_field_content_values_inner import CreateDocumentTemplateRequestFieldsInnerFieldContentValuesInner as CreateDocumentTemplateRequestFieldsInnerFieldContentValuesInner
from tl_ninjarmm.models.create_itam_tag_request import CreateItamTagRequest as CreateItamTagRequest
from tl_ninjarmm.models.create_knowledge_base_articles200_response_inner import CreateKnowledgeBaseArticles200ResponseInner as CreateKnowledgeBaseArticles200ResponseInner
from tl_ninjarmm.models.create_knowledge_base_articles200_response_inner_attachments_inner import CreateKnowledgeBaseArticles200ResponseInnerAttachmentsInner as CreateKnowledgeBaseArticles200ResponseInnerAttachmentsInner
from tl_ninjarmm.models.create_knowledge_base_articles200_response_inner_attachments_inner_metadata import CreateKnowledgeBaseArticles200ResponseInnerAttachmentsInnerMetadata as CreateKnowledgeBaseArticles200ResponseInnerAttachmentsInnerMetadata
from tl_ninjarmm.models.create_knowledge_base_articles_request_inner import CreateKnowledgeBaseArticlesRequestInner as CreateKnowledgeBaseArticlesRequestInner
from tl_ninjarmm.models.create_knowledge_base_articles_request_inner_content import CreateKnowledgeBaseArticlesRequestInnerContent as CreateKnowledgeBaseArticlesRequestInnerContent
from tl_ninjarmm.models.create_organization_checklists_request_inner import CreateOrganizationChecklistsRequestInner as CreateOrganizationChecklistsRequestInner
from tl_ninjarmm.models.create_organization_default_response import CreateOrganizationDefaultResponse as CreateOrganizationDefaultResponse
from tl_ninjarmm.models.create_organization_default_response_locations_inner import CreateOrganizationDefaultResponseLocationsInner as CreateOrganizationDefaultResponseLocationsInner
from tl_ninjarmm.models.create_organization_default_response_settings import CreateOrganizationDefaultResponseSettings as CreateOrganizationDefaultResponseSettings
from tl_ninjarmm.models.create_organization_default_response_settings_trayicon import CreateOrganizationDefaultResponseSettingsTrayicon as CreateOrganizationDefaultResponseSettingsTrayicon
from tl_ninjarmm.models.create_organization_document_request import CreateOrganizationDocumentRequest as CreateOrganizationDocumentRequest
from tl_ninjarmm.models.create_organization_documents_request_inner import CreateOrganizationDocumentsRequestInner as CreateOrganizationDocumentsRequestInner
from tl_ninjarmm.models.create_organization_request import CreateOrganizationRequest as CreateOrganizationRequest
from tl_ninjarmm.models.create_organization_request_locations_inner import CreateOrganizationRequestLocationsInner as CreateOrganizationRequestLocationsInner
from tl_ninjarmm.models.create_organization_request_policies_inner import CreateOrganizationRequestPoliciesInner as CreateOrganizationRequestPoliciesInner
from tl_ninjarmm.models.create_policy_request import CreatePolicyRequest as CreatePolicyRequest
from tl_ninjarmm.models.create_related_item200_response import CreateRelatedItem200Response as CreateRelatedItem200Response
from tl_ninjarmm.models.create_related_item_for_entity_request import CreateRelatedItemForEntityRequest as CreateRelatedItemForEntityRequest
from tl_ninjarmm.models.create_request import CreateRequest as CreateRequest
from tl_ninjarmm.models.create_request_attributes_inner import CreateRequestAttributesInner as CreateRequestAttributesInner
from tl_ninjarmm.models.create_request_cc import CreateRequestCc as CreateRequestCc
from tl_ninjarmm.models.create_request_description import CreateRequestDescription as CreateRequestDescription
from tl_ninjarmm.models.create_secure_related_item_for_entity_request import CreateSecureRelatedItemForEntityRequest as CreateSecureRelatedItemForEntityRequest
from tl_ninjarmm.models.create_tag200_response import CreateTag200Response as CreateTag200Response
from tl_ninjarmm.models.create_tag_request import CreateTagRequest as CreateTagRequest
from tl_ninjarmm.models.create_windows_event_policy_condition_request import CreateWindowsEventPolicyConditionRequest as CreateWindowsEventPolicyConditionRequest
from tl_ninjarmm.models.credential_reference import CredentialReference as CredentialReference
from tl_ninjarmm.models.cursor import Cursor as Cursor
from tl_ninjarmm.models.custom_field_policy_condition_response import CustomFieldPolicyConditionResponse as CustomFieldPolicyConditionResponse
from tl_ninjarmm.models.custom_fields_policy_condition_create_request import CustomFieldsPolicyConditionCreateRequest as CustomFieldsPolicyConditionCreateRequest
from tl_ninjarmm.models.device import Device as Device
from tl_ninjarmm.models.device_antivirus_status import DeviceAntivirusStatus as DeviceAntivirusStatus
from tl_ninjarmm.models.device_antivirus_threat import DeviceAntivirusThreat as DeviceAntivirusThreat
from tl_ninjarmm.models.device_application import DeviceApplication as DeviceApplication
from tl_ninjarmm.models.device_computer_system import DeviceComputerSystem as DeviceComputerSystem
from tl_ninjarmm.models.device_credential_options import DeviceCredentialOptions as DeviceCredentialOptions
from tl_ninjarmm.models.device_disk_drive import DeviceDiskDrive as DeviceDiskDrive
from tl_ninjarmm.models.device_health_report import DeviceHealthReport as DeviceHealthReport
from tl_ninjarmm.models.device_health_summary import DeviceHealthSummary as DeviceHealthSummary
from tl_ninjarmm.models.device_id_list import DeviceIDList as DeviceIDList
from tl_ninjarmm.models.device_link import DeviceLink as DeviceLink
from tl_ninjarmm.models.device_logged_on_user import DeviceLoggedOnUser as DeviceLoggedOnUser
from tl_ninjarmm.models.device_mutable_properties import DeviceMutableProperties as DeviceMutableProperties
from tl_ninjarmm.models.device_network_interfaces import DeviceNetworkInterfaces as DeviceNetworkInterfaces
from tl_ninjarmm.models.device_os_patch import DeviceOSPatch as DeviceOSPatch
from tl_ninjarmm.models.device_operating_system import DeviceOperatingSystem as DeviceOperatingSystem
from tl_ninjarmm.models.device_policy_overrides import DevicePolicyOverrides as DevicePolicyOverrides
from tl_ninjarmm.models.device_processor import DeviceProcessor as DeviceProcessor
from tl_ninjarmm.models.device_raid_controller import DeviceRAIDController as DeviceRAIDController
from tl_ninjarmm.models.device_raid_drive import DeviceRAIDDrive as DeviceRAIDDrive
from tl_ninjarmm.models.device_scripting_options import DeviceScriptingOptions as DeviceScriptingOptions
from tl_ninjarmm.models.device_search_match import DeviceSearchMatch as DeviceSearchMatch
from tl_ninjarmm.models.device_search_results import DeviceSearchResults as DeviceSearchResults
from tl_ninjarmm.models.device_software_patch import DeviceSoftwarePatch as DeviceSoftwarePatch
from tl_ninjarmm.models.device_usage_report import DeviceUsageReport as DeviceUsageReport
from tl_ninjarmm.models.device_volume import DeviceVolume as DeviceVolume
from tl_ninjarmm.models.device_windows_service import DeviceWindowsService as DeviceWindowsService
from tl_ninjarmm.models.disk_drive import DiskDrive as DiskDrive
from tl_ninjarmm.models.disk_drive_report import DiskDriveReport as DiskDriveReport
from tl_ninjarmm.models.document_attribute_content_public_api import DocumentAttributeContentPublicApi as DocumentAttributeContentPublicApi
from tl_ninjarmm.models.document_attribute_content_value_public_api import DocumentAttributeContentValuePublicApi as DocumentAttributeContentValuePublicApi
from tl_ninjarmm.models.document_item_public_api_dto import DocumentItemPublicApiDTO as DocumentItemPublicApiDTO
from tl_ninjarmm.models.document_template_public_api_dto import DocumentTemplatePublicApiDTO as DocumentTemplatePublicApiDTO
from tl_ninjarmm.models.end_user_customization import EndUserCustomization as EndUserCustomization
from tl_ninjarmm.models.feature_settings import FeatureSettings as FeatureSettings
from tl_ninjarmm.models.fetch_all_scan_groups200_response_inner import FetchAllScanGroups200ResponseInner as FetchAllScanGroups200ResponseInner
from tl_ninjarmm.models.form_data_body_part import FormDataBodyPart as FormDataBodyPart
from tl_ninjarmm.models.form_data_content_disposition import FormDataContentDisposition as FormDataContentDisposition
from tl_ninjarmm.models.generate_installer_request_dto import GenerateInstallerRequestDto as GenerateInstallerRequestDto
from tl_ninjarmm.models.get_activities_default_response import GetActivitiesDefaultResponse as GetActivitiesDefaultResponse
from tl_ninjarmm.models.get_all_user_and_contacts200_response_inner import GetAllUserAndContacts200ResponseInner as GetAllUserAndContacts200ResponseInner
from tl_ninjarmm.models.get_antivirus_status_report_default_response import GetAntivirusStatusReportDefaultResponse as GetAntivirusStatusReportDefaultResponse
from tl_ninjarmm.models.get_antivirus_status_report_default_response_results_inner import GetAntivirusStatusReportDefaultResponseResultsInner as GetAntivirusStatusReportDefaultResponseResultsInner
from tl_ninjarmm.models.get_antivirus_threats_default_response import GetAntivirusThreatsDefaultResponse as GetAntivirusThreatsDefaultResponse
from tl_ninjarmm.models.get_antivirus_threats_default_response_results_inner import GetAntivirusThreatsDefaultResponseResultsInner as GetAntivirusThreatsDefaultResponseResultsInner
from tl_ninjarmm.models.get_automation_scripts_default_response_inner import GetAutomationScriptsDefaultResponseInner as GetAutomationScriptsDefaultResponseInner
from tl_ninjarmm.models.get_automation_scripts_default_response_inner_script_variables_inner import GetAutomationScriptsDefaultResponseInnerScriptVariablesInner as GetAutomationScriptsDefaultResponseInnerScriptVariablesInner
from tl_ninjarmm.models.get_boards_default_response_inner import GetBoardsDefaultResponseInner as GetBoardsDefaultResponseInner
from tl_ninjarmm.models.get_boards_default_response_inner_conditions import GetBoardsDefaultResponseInnerConditions as GetBoardsDefaultResponseInnerConditions
from tl_ninjarmm.models.get_boards_default_response_inner_conditions_any_inner import GetBoardsDefaultResponseInnerConditionsAnyInner as GetBoardsDefaultResponseInnerConditionsAnyInner
from tl_ninjarmm.models.get_computer_systems_default_response import GetComputerSystemsDefaultResponse as GetComputerSystemsDefaultResponse
from tl_ninjarmm.models.get_computer_systems_default_response_results_inner import GetComputerSystemsDefaultResponseResultsInner as GetComputerSystemsDefaultResponseResultsInner
from tl_ninjarmm.models.get_contacts_default_response_inner import GetContactsDefaultResponseInner as GetContactsDefaultResponseInner
from tl_ninjarmm.models.get_custom_fields_detailed_report_default_response import GetCustomFieldsDetailedReportDefaultResponse as GetCustomFieldsDetailedReportDefaultResponse
from tl_ninjarmm.models.get_custom_fields_detailed_report_default_response_results_inner import GetCustomFieldsDetailedReportDefaultResponseResultsInner as GetCustomFieldsDetailedReportDefaultResponseResultsInner
from tl_ninjarmm.models.get_custom_fields_detailed_report_default_response_results_inner_fields_inner import GetCustomFieldsDetailedReportDefaultResponseResultsInnerFieldsInner as GetCustomFieldsDetailedReportDefaultResponseResultsInnerFieldsInner
from tl_ninjarmm.models.get_custom_fields_detailed_report_default_response_results_inner_fields_inner_updated_by import GetCustomFieldsDetailedReportDefaultResponseResultsInnerFieldsInnerUpdatedBy as GetCustomFieldsDetailedReportDefaultResponseResultsInnerFieldsInnerUpdatedBy
from tl_ninjarmm.models.get_custom_fields_policy_conditions_default_response_inner import GetCustomFieldsPolicyConditionsDefaultResponseInner as GetCustomFieldsPolicyConditionsDefaultResponseInner
from tl_ninjarmm.models.get_custom_fields_policy_conditions_default_response_inner_inheritance import GetCustomFieldsPolicyConditionsDefaultResponseInnerInheritance as GetCustomFieldsPolicyConditionsDefaultResponseInnerInheritance
from tl_ninjarmm.models.get_custom_fields_policy_conditions_default_response_inner_match_all_inner import GetCustomFieldsPolicyConditionsDefaultResponseInnerMatchAllInner as GetCustomFieldsPolicyConditionsDefaultResponseInnerMatchAllInner
from tl_ninjarmm.models.get_custom_fields_policy_conditions_default_response_inner_scripts_inner import GetCustomFieldsPolicyConditionsDefaultResponseInnerScriptsInner as GetCustomFieldsPolicyConditionsDefaultResponseInnerScriptsInner
from tl_ninjarmm.models.get_custom_fields_policy_conditions_default_response_inner_scripts_inner_script_variables_inner import GetCustomFieldsPolicyConditionsDefaultResponseInnerScriptsInnerScriptVariablesInner as GetCustomFieldsPolicyConditionsDefaultResponseInnerScriptsInnerScriptVariablesInner
from tl_ninjarmm.models.get_custom_fields_report_default_response import GetCustomFieldsReportDefaultResponse as GetCustomFieldsReportDefaultResponse
from tl_ninjarmm.models.get_custom_fields_report_default_response_results_inner import GetCustomFieldsReportDefaultResponseResultsInner as GetCustomFieldsReportDefaultResponseResultsInner
from tl_ninjarmm.models.get_device200_response import GetDevice200Response as GetDevice200Response
from tl_ninjarmm.models.get_device200_response_maintenance import GetDevice200ResponseMaintenance as GetDevice200ResponseMaintenance
from tl_ninjarmm.models.get_device200_response_notes_inner import GetDevice200ResponseNotesInner as GetDevice200ResponseNotesInner
from tl_ninjarmm.models.get_device200_response_references import GetDevice200ResponseReferences as GetDevice200ResponseReferences
from tl_ninjarmm.models.get_device200_response_references_backup_usage import GetDevice200ResponseReferencesBackupUsage as GetDevice200ResponseReferencesBackupUsage
from tl_ninjarmm.models.get_device200_response_references_role import GetDevice200ResponseReferencesRole as GetDevice200ResponseReferencesRole
from tl_ninjarmm.models.get_device200_response_references_role_policy import GetDevice200ResponseReferencesRolePolicy as GetDevice200ResponseReferencesRolePolicy
from tl_ninjarmm.models.get_device200_response_references_warranty import GetDevice200ResponseReferencesWarranty as GetDevice200ResponseReferencesWarranty
from tl_ninjarmm.models.get_device_active_jobs_default_response_inner import GetDeviceActiveJobsDefaultResponseInner as GetDeviceActiveJobsDefaultResponseInner
from tl_ninjarmm.models.get_device_active_jobs_default_response_inner_device import GetDeviceActiveJobsDefaultResponseInnerDevice as GetDeviceActiveJobsDefaultResponseInnerDevice
from tl_ninjarmm.models.get_device_activities_default_response import GetDeviceActivitiesDefaultResponse as GetDeviceActivitiesDefaultResponse
from tl_ninjarmm.models.get_device_activities_default_response_activities_inner import GetDeviceActivitiesDefaultResponseActivitiesInner as GetDeviceActivitiesDefaultResponseActivitiesInner
from tl_ninjarmm.models.get_device_alerts_default_response_inner import GetDeviceAlertsDefaultResponseInner as GetDeviceAlertsDefaultResponseInner
from tl_ninjarmm.models.get_device_disk_drives_default_response_inner import GetDeviceDiskDrivesDefaultResponseInner as GetDeviceDiskDrivesDefaultResponseInner
from tl_ninjarmm.models.get_device_global_custom_fields_default_response_inner import GetDeviceGlobalCustomFieldsDefaultResponseInner as GetDeviceGlobalCustomFieldsDefaultResponseInner
from tl_ninjarmm.models.get_device_global_custom_fields_default_response_inner_content import GetDeviceGlobalCustomFieldsDefaultResponseInnerContent as GetDeviceGlobalCustomFieldsDefaultResponseInnerContent
from tl_ninjarmm.models.get_device_global_custom_fields_default_response_inner_content_end_user_customization import GetDeviceGlobalCustomFieldsDefaultResponseInnerContentEndUserCustomization as GetDeviceGlobalCustomFieldsDefaultResponseInnerContentEndUserCustomization
from tl_ninjarmm.models.get_device_global_custom_fields_default_response_inner_content_values_inner import GetDeviceGlobalCustomFieldsDefaultResponseInnerContentValuesInner as GetDeviceGlobalCustomFieldsDefaultResponseInnerContentValuesInner
from tl_ninjarmm.models.get_device_health_report_default_response import GetDeviceHealthReportDefaultResponse as GetDeviceHealthReportDefaultResponse
from tl_ninjarmm.models.get_device_health_report_default_response_results_inner import GetDeviceHealthReportDefaultResponseResultsInner as GetDeviceHealthReportDefaultResponseResultsInner
from tl_ninjarmm.models.get_device_installed_os_patches_default_response_inner import GetDeviceInstalledOSPatchesDefaultResponseInner as GetDeviceInstalledOSPatchesDefaultResponseInner
from tl_ninjarmm.models.get_device_installed_software_patches_default_response_inner import GetDeviceInstalledSoftwarePatchesDefaultResponseInner as GetDeviceInstalledSoftwarePatchesDefaultResponseInner
from tl_ninjarmm.models.get_device_last_logged_on_user_default_response import GetDeviceLastLoggedOnUserDefaultResponse as GetDeviceLastLoggedOnUserDefaultResponse
from tl_ninjarmm.models.get_device_link_default_response import GetDeviceLinkDefaultResponse as GetDeviceLinkDefaultResponse
from tl_ninjarmm.models.get_device_network_interfaces_default_response_inner import GetDeviceNetworkInterfacesDefaultResponseInner as GetDeviceNetworkInterfacesDefaultResponseInner
from tl_ninjarmm.models.get_device_processors_default_response_inner import GetDeviceProcessorsDefaultResponseInner as GetDeviceProcessorsDefaultResponseInner
from tl_ninjarmm.models.get_device_services_default_response_inner import GetDeviceServicesDefaultResponseInner as GetDeviceServicesDefaultResponseInner
from tl_ninjarmm.models.get_device_software_default_response_inner import GetDeviceSoftwareDefaultResponseInner as GetDeviceSoftwareDefaultResponseInner
from tl_ninjarmm.models.get_device_usage200_response import GetDeviceUsage200Response as GetDeviceUsage200Response
from tl_ninjarmm.models.get_device_volumes_default_response_inner import GetDeviceVolumesDefaultResponseInner as GetDeviceVolumesDefaultResponseInner
from tl_ninjarmm.models.get_device_volumes_default_response_inner_bit_locker_status import GetDeviceVolumesDefaultResponseInnerBitLockerStatus as GetDeviceVolumesDefaultResponseInnerBitLockerStatus
from tl_ninjarmm.models.get_disk_drives_default_response import GetDiskDrivesDefaultResponse as GetDiskDrivesDefaultResponse
from tl_ninjarmm.models.get_disk_drives_default_response_results_inner import GetDiskDrivesDefaultResponseResultsInner as GetDiskDrivesDefaultResponseResultsInner
from tl_ninjarmm.models.get_document_templates_with_attributes200_response_inner import GetDocumentTemplatesWithAttributes200ResponseInner as GetDocumentTemplatesWithAttributes200ResponseInner
from tl_ninjarmm.models.get_document_templates_with_attributes200_response_inner_archived_by import GetDocumentTemplatesWithAttributes200ResponseInnerArchivedBy as GetDocumentTemplatesWithAttributes200ResponseInnerArchivedBy
from tl_ninjarmm.models.get_document_templates_with_attributes200_response_inner_fields_inner import GetDocumentTemplatesWithAttributes200ResponseInnerFieldsInner as GetDocumentTemplatesWithAttributes200ResponseInnerFieldsInner
from tl_ninjarmm.models.get_document_templates_with_attributes200_response_inner_fields_inner_field_content import GetDocumentTemplatesWithAttributes200ResponseInnerFieldsInnerFieldContent as GetDocumentTemplatesWithAttributes200ResponseInnerFieldsInnerFieldContent
from tl_ninjarmm.models.get_document_templates_with_attributes200_response_inner_fields_inner_field_content_advanced_settings import GetDocumentTemplatesWithAttributes200ResponseInnerFieldsInnerFieldContentAdvancedSettings as GetDocumentTemplatesWithAttributes200ResponseInnerFieldsInnerFieldContentAdvancedSettings
from tl_ninjarmm.models.get_document_templates_with_attributes200_response_inner_fields_inner_field_content_advanced_settings_complexity_rules import GetDocumentTemplatesWithAttributes200ResponseInnerFieldsInnerFieldContentAdvancedSettingsComplexityRules as GetDocumentTemplatesWithAttributes200ResponseInnerFieldsInnerFieldContentAdvancedSettingsComplexityRules
from tl_ninjarmm.models.get_document_templates_with_attributes200_response_inner_fields_inner_field_content_advanced_settings_date_filters import GetDocumentTemplatesWithAttributes200ResponseInnerFieldsInnerFieldContentAdvancedSettingsDateFilters as GetDocumentTemplatesWithAttributes200ResponseInnerFieldsInnerFieldContentAdvancedSettingsDateFilters
from tl_ninjarmm.models.get_document_templates_with_attributes200_response_inner_fields_inner_field_content_advanced_settings_numeric_range import GetDocumentTemplatesWithAttributes200ResponseInnerFieldsInnerFieldContentAdvancedSettingsNumericRange as GetDocumentTemplatesWithAttributes200ResponseInnerFieldsInnerFieldContentAdvancedSettingsNumericRange
from tl_ninjarmm.models.get_document_templates_with_attributes200_response_inner_fields_inner_field_content_values_inner import GetDocumentTemplatesWithAttributes200ResponseInnerFieldsInnerFieldContentValuesInner as GetDocumentTemplatesWithAttributes200ResponseInnerFieldsInnerFieldContentValuesInner
from tl_ninjarmm.models.get_enabled_notification_channels_default_response_inner import GetEnabledNotificationChannelsDefaultResponseInner as GetEnabledNotificationChannelsDefaultResponseInner
from tl_ninjarmm.models.get_end_users_default_response_inner import GetEndUsersDefaultResponseInner as GetEndUsersDefaultResponseInner
from tl_ninjarmm.models.get_groups_default_response_inner import GetGroupsDefaultResponseInner as GetGroupsDefaultResponseInner
from tl_ninjarmm.models.get_installed_os_patches_default_response import GetInstalledOSPatchesDefaultResponse as GetInstalledOSPatchesDefaultResponse
from tl_ninjarmm.models.get_installed_os_patches_default_response_results_inner import GetInstalledOSPatchesDefaultResponseResultsInner as GetInstalledOSPatchesDefaultResponseResultsInner
from tl_ninjarmm.models.get_installed_software_patches_default_response import GetInstalledSoftwarePatchesDefaultResponse as GetInstalledSoftwarePatchesDefaultResponse
from tl_ninjarmm.models.get_installed_software_patches_default_response_results_inner import GetInstalledSoftwarePatchesDefaultResponseResultsInner as GetInstalledSoftwarePatchesDefaultResponseResultsInner
from tl_ninjarmm.models.get_installer_default_response import GetInstallerDefaultResponse as GetInstallerDefaultResponse
from tl_ninjarmm.models.get_installer_request import GetInstallerRequest as GetInstallerRequest
from tl_ninjarmm.models.get_installer_request_content import GetInstallerRequestContent as GetInstallerRequestContent
from tl_ninjarmm.models.get_integrity_check_jobs200_response import GetIntegrityCheckJobs200Response as GetIntegrityCheckJobs200Response
from tl_ninjarmm.models.get_integrity_check_jobs200_response_cursor import GetIntegrityCheckJobs200ResponseCursor as GetIntegrityCheckJobs200ResponseCursor
from tl_ninjarmm.models.get_integrity_check_jobs200_response_results_inner import GetIntegrityCheckJobs200ResponseResultsInner as GetIntegrityCheckJobs200ResponseResultsInner
from tl_ninjarmm.models.get_itam_tags_public_api_response import GetItamTagsPublicApiResponse as GetItamTagsPublicApiResponse
from tl_ninjarmm.models.get_itam_tags_response import GetItamTagsResponse as GetItamTagsResponse
from tl_ninjarmm.models.get_knowledge_base_folder_content200_response import GetKnowledgeBaseFolderContent200Response as GetKnowledgeBaseFolderContent200Response
from tl_ninjarmm.models.get_knowledge_base_folder_content200_response_content_inner import GetKnowledgeBaseFolderContent200ResponseContentInner as GetKnowledgeBaseFolderContent200ResponseContentInner
from tl_ninjarmm.models.get_last_logged_on_users_report_default_response import GetLastLoggedOnUsersReportDefaultResponse as GetLastLoggedOnUsersReportDefaultResponse
from tl_ninjarmm.models.get_last_logged_on_users_report_default_response_results_inner import GetLastLoggedOnUsersReportDefaultResponseResultsInner as GetLastLoggedOnUsersReportDefaultResponseResultsInner
from tl_ninjarmm.models.get_location_usage200_response import GetLocationUsage200Response as GetLocationUsage200Response
from tl_ninjarmm.models.get_locations_default_response_inner import GetLocationsDefaultResponseInner as GetLocationsDefaultResponseInner
from tl_ninjarmm.models.get_network_interfaces_default_response import GetNetworkInterfacesDefaultResponse as GetNetworkInterfacesDefaultResponse
from tl_ninjarmm.models.get_network_interfaces_default_response_results_inner import GetNetworkInterfacesDefaultResponseResultsInner as GetNetworkInterfacesDefaultResponseResultsInner
from tl_ninjarmm.models.get_operating_systems_default_response import GetOperatingSystemsDefaultResponse as GetOperatingSystemsDefaultResponse
from tl_ninjarmm.models.get_operating_systems_default_response_results_inner import GetOperatingSystemsDefaultResponseResultsInner as GetOperatingSystemsDefaultResponseResultsInner
from tl_ninjarmm.models.get_organizations_default_response_inner import GetOrganizationsDefaultResponseInner as GetOrganizationsDefaultResponseInner
from tl_ninjarmm.models.get_policy_overrides1_default_response import GetPolicyOverrides1DefaultResponse as GetPolicyOverrides1DefaultResponse
from tl_ninjarmm.models.get_policy_overrides1_default_response_results_inner import GetPolicyOverrides1DefaultResponseResultsInner as GetPolicyOverrides1DefaultResponseResultsInner
from tl_ninjarmm.models.get_policy_overrides_default_response import GetPolicyOverridesDefaultResponse as GetPolicyOverridesDefaultResponse
from tl_ninjarmm.models.get_processors_default_response import GetProcessorsDefaultResponse as GetProcessorsDefaultResponse
from tl_ninjarmm.models.get_processors_default_response_results_inner import GetProcessorsDefaultResponseResultsInner as GetProcessorsDefaultResponseResultsInner
from tl_ninjarmm.models.get_raid_controller_report_default_response import GetRAIDControllerReportDefaultResponse as GetRAIDControllerReportDefaultResponse
from tl_ninjarmm.models.get_raid_controller_report_default_response_results_inner import GetRAIDControllerReportDefaultResponseResultsInner as GetRAIDControllerReportDefaultResponseResultsInner
from tl_ninjarmm.models.get_raid_drive_report_default_response import GetRAIDDriveReportDefaultResponse as GetRAIDDriveReportDefaultResponse
from tl_ninjarmm.models.get_raid_drive_report_default_response_results_inner import GetRAIDDriveReportDefaultResponseResultsInner as GetRAIDDriveReportDefaultResponseResultsInner
from tl_ninjarmm.models.get_scheduled_tasks_default_response_inner import GetScheduledTasksDefaultResponseInner as GetScheduledTasksDefaultResponseInner
from tl_ninjarmm.models.get_scoped_custom_fields_detailed_report_default_response import GetScopedCustomFieldsDetailedReportDefaultResponse as GetScopedCustomFieldsDetailedReportDefaultResponse
from tl_ninjarmm.models.get_scoped_custom_fields_detailed_report_default_response_results_inner import GetScopedCustomFieldsDetailedReportDefaultResponseResultsInner as GetScopedCustomFieldsDetailedReportDefaultResponseResultsInner
from tl_ninjarmm.models.get_scoped_custom_fields_report_default_response import GetScopedCustomFieldsReportDefaultResponse as GetScopedCustomFieldsReportDefaultResponse
from tl_ninjarmm.models.get_scoped_custom_fields_report_default_response_results_inner import GetScopedCustomFieldsReportDefaultResponseResultsInner as GetScopedCustomFieldsReportDefaultResponseResultsInner
from tl_ninjarmm.models.get_software_default_response import GetSoftwareDefaultResponse as GetSoftwareDefaultResponse
from tl_ninjarmm.models.get_software_default_response_results_inner import GetSoftwareDefaultResponseResultsInner as GetSoftwareDefaultResponseResultsInner
from tl_ninjarmm.models.get_software_products_default_response_inner import GetSoftwareProductsDefaultResponseInner as GetSoftwareProductsDefaultResponseInner
from tl_ninjarmm.models.get_tags200_response import GetTags200Response as GetTags200Response
from tl_ninjarmm.models.get_tags200_response_tags_inner import GetTags200ResponseTagsInner as GetTags200ResponseTagsInner
from tl_ninjarmm.models.get_tags200_response_tags_inner_created_by import GetTags200ResponseTagsInnerCreatedBy as GetTags200ResponseTagsInnerCreatedBy
from tl_ninjarmm.models.get_ticket_attributes_default_response_inner import GetTicketAttributesDefaultResponseInner as GetTicketAttributesDefaultResponseInner
from tl_ninjarmm.models.get_ticket_form_by_id_default_response import GetTicketFormByIdDefaultResponse as GetTicketFormByIdDefaultResponse
from tl_ninjarmm.models.get_ticket_form_by_id_default_response_content import GetTicketFormByIdDefaultResponseContent as GetTicketFormByIdDefaultResponseContent
from tl_ninjarmm.models.get_ticket_form_by_id_default_response_content_timer_settings import GetTicketFormByIdDefaultResponseContentTimerSettings as GetTicketFormByIdDefaultResponseContentTimerSettings
from tl_ninjarmm.models.get_ticket_log_entries_by_ticket_id_default_response_inner import GetTicketLogEntriesByTicketIdDefaultResponseInner as GetTicketLogEntriesByTicketIdDefaultResponseInner
from tl_ninjarmm.models.get_ticket_log_entries_by_ticket_id_default_response_inner_automation import GetTicketLogEntriesByTicketIdDefaultResponseInnerAutomation as GetTicketLogEntriesByTicketIdDefaultResponseInnerAutomation
from tl_ninjarmm.models.get_ticket_log_entries_by_ticket_id_default_response_inner_technicians_tagged_metadata_inner import GetTicketLogEntriesByTicketIdDefaultResponseInnerTechniciansTaggedMetadataInner as GetTicketLogEntriesByTicketIdDefaultResponseInnerTechniciansTaggedMetadataInner
from tl_ninjarmm.models.get_ticket_log_entries_by_ticket_id_default_response_inner_ticket_time_entry import GetTicketLogEntriesByTicketIdDefaultResponseInnerTicketTimeEntry as GetTicketLogEntriesByTicketIdDefaultResponseInnerTicketTimeEntry
from tl_ninjarmm.models.get_ticket_log_entries_by_ticket_id_default_response_inner_ticket_time_entry_agreement import GetTicketLogEntriesByTicketIdDefaultResponseInnerTicketTimeEntryAgreement as GetTicketLogEntriesByTicketIdDefaultResponseInnerTicketTimeEntryAgreement
from tl_ninjarmm.models.get_tickets_by_board_default_response import GetTicketsByBoardDefaultResponse as GetTicketsByBoardDefaultResponse
from tl_ninjarmm.models.get_tickets_by_board_default_response_metadata import GetTicketsByBoardDefaultResponseMetadata as GetTicketsByBoardDefaultResponseMetadata
from tl_ninjarmm.models.get_tickets_by_board_default_response_metadata_attributes_value import GetTicketsByBoardDefaultResponseMetadataAttributesValue as GetTicketsByBoardDefaultResponseMetadataAttributesValue
from tl_ninjarmm.models.get_tickets_by_board_request import GetTicketsByBoardRequest as GetTicketsByBoardRequest
from tl_ninjarmm.models.get_tickets_by_board_request_sort_by_inner import GetTicketsByBoardRequestSortByInner as GetTicketsByBoardRequestSortByInner
from tl_ninjarmm.models.get_volumes_default_response import GetVolumesDefaultResponse as GetVolumesDefaultResponse
from tl_ninjarmm.models.get_volumes_default_response_results_inner import GetVolumesDefaultResponseResultsInner as GetVolumesDefaultResponseResultsInner
from tl_ninjarmm.models.get_windows_event_policy_conditions_default_response_inner import GetWindowsEventPolicyConditionsDefaultResponseInner as GetWindowsEventPolicyConditionsDefaultResponseInner
from tl_ninjarmm.models.get_windows_event_policy_conditions_default_response_inner_occurrence import GetWindowsEventPolicyConditionsDefaultResponseInnerOccurrence as GetWindowsEventPolicyConditionsDefaultResponseInnerOccurrence
from tl_ninjarmm.models.get_windows_event_policy_conditions_default_response_inner_text import GetWindowsEventPolicyConditionsDefaultResponseInnerText as GetWindowsEventPolicyConditionsDefaultResponseInnerText
from tl_ninjarmm.models.get_windows_services_report_default_response import GetWindowsServicesReportDefaultResponse as GetWindowsServicesReportDefaultResponse
from tl_ninjarmm.models.get_windows_services_report_default_response_results_inner import GetWindowsServicesReportDefaultResponseResultsInner as GetWindowsServicesReportDefaultResponseResultsInner
from tl_ninjarmm.models.group import Group as Group
from tl_ninjarmm.models.http_header import HTTPHeader as HTTPHeader
from tl_ninjarmm.models.installer_content import InstallerContent as InstallerContent
from tl_ninjarmm.models.itam_manage_asset_request_public_api_dto import ItamManageAssetRequestPublicApiDTO as ItamManageAssetRequestPublicApiDTO
from tl_ninjarmm.models.itam_set_asset_tags_request_public_api_dto import ItamSetAssetTagsRequestPublicApiDTO as ItamSetAssetTagsRequestPublicApiDTO
from tl_ninjarmm.models.itam_tag_dto import ItamTagDTO as ItamTagDTO
from tl_ninjarmm.models.itam_tag_public_api_dto import ItamTagPublicApiDTO as ItamTagPublicApiDTO
from tl_ninjarmm.models.job import Job as Job
from tl_ninjarmm.models.knowledge_base_article_bulk_create_public_api_request import KnowledgeBaseArticleBulkCreatePublicApiRequest as KnowledgeBaseArticleBulkCreatePublicApiRequest
from tl_ninjarmm.models.knowledge_base_article_bulk_update_public_api_request import KnowledgeBaseArticleBulkUpdatePublicApiRequest as KnowledgeBaseArticleBulkUpdatePublicApiRequest
from tl_ninjarmm.models.knowledge_base_article_public_api_content import KnowledgeBaseArticlePublicApiContent as KnowledgeBaseArticlePublicApiContent
from tl_ninjarmm.models.knowledge_base_article_public_api_dto import KnowledgeBaseArticlePublicApiDTO as KnowledgeBaseArticlePublicApiDTO
from tl_ninjarmm.models.knowledge_base_attachment_public_api_dto import KnowledgeBaseAttachmentPublicApiDTO as KnowledgeBaseAttachmentPublicApiDTO
from tl_ninjarmm.models.knowledge_base_folder_item_public_api_dto import KnowledgeBaseFolderItemPublicApiDTO as KnowledgeBaseFolderItemPublicApiDTO
from tl_ninjarmm.models.knowledge_base_folder_public_api_dto import KnowledgeBaseFolderPublicApiDTO as KnowledgeBaseFolderPublicApiDTO
from tl_ninjarmm.models.link import Link as Link
from tl_ninjarmm.models.location import Location as Location
from tl_ninjarmm.models.location_backup_usage_summary import LocationBackupUsageSummary as LocationBackupUsageSummary
from tl_ninjarmm.models.location_model import LocationModel as LocationModel
from tl_ninjarmm.models.location_with_organization_ref import LocationWithOrganizationRef as LocationWithOrganizationRef
from tl_ninjarmm.models.lockhart_integrity_check_job import LockhartIntegrityCheckJob as LockhartIntegrityCheckJob
from tl_ninjarmm.models.lockhart_integrity_check_job_creation_request import LockhartIntegrityCheckJobCreationRequest as LockhartIntegrityCheckJobCreationRequest
from tl_ninjarmm.models.lockhart_integrity_check_job_creation_response import LockhartIntegrityCheckJobCreationResponse as LockhartIntegrityCheckJobCreationResponse
from tl_ninjarmm.models.lockhart_integrity_check_job_report import LockhartIntegrityCheckJobReport as LockhartIntegrityCheckJobReport
from tl_ninjarmm.models.lockhart_integrity_check_job_report_results_inner import LockhartIntegrityCheckJobReportResultsInner as LockhartIntegrityCheckJobReportResultsInner
from tl_ninjarmm.models.logged_on_user import LoggedOnUser as LoggedOnUser
from tl_ninjarmm.models.logged_on_users_report import LoggedOnUsersReport as LoggedOnUsersReport
from tl_ninjarmm.models.maintenance import Maintenance as Maintenance
from tl_ninjarmm.models.maintenance_settings import MaintenanceSettings as MaintenanceSettings
from tl_ninjarmm.models.mdm_device import MdmDevice as MdmDevice
from tl_ninjarmm.models.memory import Memory as Memory
from tl_ninjarmm.models.merge_itam_tags_public_api_request import MergeItamTagsPublicApiRequest as MergeItamTagsPublicApiRequest
from tl_ninjarmm.models.merge_tags_request import MergeTagsRequest as MergeTagsRequest
from tl_ninjarmm.models.move_public_api_request import MovePublicApiRequest as MovePublicApiRequest
from tl_ninjarmm.models.move_request import MoveRequest as MoveRequest
from tl_ninjarmm.models.multi_part import MultiPart as MultiPart
from tl_ninjarmm.models.nms_server import NMSServer as NMSServer
from tl_ninjarmm.models.nms_target import NMSTarget as NMSTarget
from tl_ninjarmm.models.network_interface import NetworkInterface as NetworkInterface
from tl_ninjarmm.models.network_interfaces_report import NetworkInterfacesReport as NetworkInterfacesReport
from tl_ninjarmm.models.new_document_attribute_content_public_api import NewDocumentAttributeContentPublicApi as NewDocumentAttributeContentPublicApi
from tl_ninjarmm.models.new_document_attribute_content_value_public_api import NewDocumentAttributeContentValuePublicApi as NewDocumentAttributeContentValuePublicApi
from tl_ninjarmm.models.new_document_item_public_api_request import NewDocumentItemPublicApiRequest as NewDocumentItemPublicApiRequest
from tl_ninjarmm.models.new_document_template_public_api_request import NewDocumentTemplatePublicApiRequest as NewDocumentTemplatePublicApiRequest
from tl_ninjarmm.models.new_related_item_entity_request import NewRelatedItemEntityRequest as NewRelatedItemEntityRequest
from tl_ninjarmm.models.new_related_item_secure_value_request import NewRelatedItemSecureValueRequest as NewRelatedItemSecureValueRequest
from tl_ninjarmm.models.new_ticket import NewTicket as NewTicket
from tl_ninjarmm.models.new_ticket_log_entry import NewTicketLogEntry as NewTicketLogEntry
from tl_ninjarmm.models.node_activities_response import NodeActivitiesResponse as NodeActivitiesResponse
from tl_ninjarmm.models.node_approval_operation_request import NodeApprovalOperationRequest as NodeApprovalOperationRequest
from tl_ninjarmm.models.node_attribute_info import NodeAttributeInfo as NodeAttributeInfo
from tl_ninjarmm.models.node_attributes import NodeAttributes as NodeAttributes
from tl_ninjarmm.models.node_attributes_detailed import NodeAttributesDetailed as NodeAttributesDetailed
from tl_ninjarmm.models.node_attributes_detailed_report import NodeAttributesDetailedReport as NodeAttributesDetailedReport
from tl_ninjarmm.models.node_attributes_report import NodeAttributesReport as NodeAttributesReport
from tl_ninjarmm.models.node_references import NodeReferences as NodeReferences
from tl_ninjarmm.models.node_role import NodeRole as NodeRole
from tl_ninjarmm.models.node_role_policy_assignment import NodeRolePolicyAssignment as NodeRolePolicyAssignment
from tl_ninjarmm.models.node_with_detailed_references import NodeWithDetailedReferences as NodeWithDetailedReferences
from tl_ninjarmm.models.note import Note as Note
from tl_ninjarmm.models.notification_channel import NotificationChannel as NotificationChannel
from tl_ninjarmm.models.os_patch import OSPatch as OSPatch
from tl_ninjarmm.models.os_patch_report import OSPatchReport as OSPatchReport
from tl_ninjarmm.models.operating_system import OperatingSystem as OperatingSystem
from tl_ninjarmm.models.operating_systems_report import OperatingSystemsReport as OperatingSystemsReport
from tl_ninjarmm.models.organization import Organization as Organization
from tl_ninjarmm.models.organization_detailed import OrganizationDetailed as OrganizationDetailed
from tl_ninjarmm.models.organization_model import OrganizationModel as OrganizationModel
from tl_ninjarmm.models.organization_settings import OrganizationSettings as OrganizationSettings
from tl_ninjarmm.models.organization_with_locations_and_policy_assignments_model import OrganizationWithLocationsAndPolicyAssignmentsModel as OrganizationWithLocationsAndPolicyAssignmentsModel
from tl_ninjarmm.models.parameterized_header import ParameterizedHeader as ParameterizedHeader
from tl_ninjarmm.models.policy import Policy as Policy
from tl_ninjarmm.models.policy_condition_custom_field import PolicyConditionCustomField as PolicyConditionCustomField
from tl_ninjarmm.models.policy_condition_inheritance_status import PolicyConditionInheritanceStatus as PolicyConditionInheritanceStatus
from tl_ninjarmm.models.policy_condition_script import PolicyConditionScript as PolicyConditionScript
from tl_ninjarmm.models.policy_condition_script_variable import PolicyConditionScriptVariable as PolicyConditionScriptVariable
from tl_ninjarmm.models.policy_info import PolicyInfo as PolicyInfo
from tl_ninjarmm.models.policy_overrides import PolicyOverrides as PolicyOverrides
from tl_ninjarmm.models.policy_overrides_report import PolicyOverridesReport as PolicyOverridesReport
from tl_ninjarmm.models.processor import Processor as Processor
from tl_ninjarmm.models.processor_report import ProcessorReport as ProcessorReport
from tl_ninjarmm.models.promote_client_checklist_with_name_public_api_request import PromoteClientChecklistWithNamePublicApiRequest as PromoteClientChecklistWithNamePublicApiRequest
from tl_ninjarmm.models.promote_client_checklists_request_inner import PromoteClientChecklistsRequestInner as PromoteClientChecklistsRequestInner
from tl_ninjarmm.models.public_scan_group import PublicScanGroup as PublicScanGroup
from tl_ninjarmm.models.raid_controller_report import RAIDControllerReport as RAIDControllerReport
from tl_ninjarmm.models.raid_drive_report import RAIDDriveReport as RAIDDriveReport
from tl_ninjarmm.models.reboot_devices_request import RebootDevicesRequest as RebootDevicesRequest
from tl_ninjarmm.models.reboot_request import RebootRequest as RebootRequest
from tl_ninjarmm.models.related_item_public_api_dto import RelatedItemPublicApiDTO as RelatedItemPublicApiDTO
from tl_ninjarmm.models.request_scripting_options_default_response import RequestScriptingOptionsDefaultResponse as RequestScriptingOptionsDefaultResponse
from tl_ninjarmm.models.request_scripting_options_default_response_categories_inner import RequestScriptingOptionsDefaultResponseCategoriesInner as RequestScriptingOptionsDefaultResponseCategoriesInner
from tl_ninjarmm.models.request_scripting_options_default_response_credentials import RequestScriptingOptionsDefaultResponseCredentials as RequestScriptingOptionsDefaultResponseCredentials
from tl_ninjarmm.models.request_scripting_options_default_response_credentials_credentials_inner import RequestScriptingOptionsDefaultResponseCredentialsCredentialsInner as RequestScriptingOptionsDefaultResponseCredentialsCredentialsInner
from tl_ninjarmm.models.request_scripting_options_default_response_scripts_inner import RequestScriptingOptionsDefaultResponseScriptsInner as RequestScriptingOptionsDefaultResponseScriptsInner
from tl_ninjarmm.models.restore_checklist_templates_request import RestoreChecklistTemplatesRequest as RestoreChecklistTemplatesRequest
from tl_ninjarmm.models.rule import Rule as Rule
from tl_ninjarmm.models.run_script_on_device_request import RunScriptOnDeviceRequest as RunScriptOnDeviceRequest
from tl_ninjarmm.models.run_script_request import RunScriptRequest as RunScriptRequest
from tl_ninjarmm.models.scheduled_task import ScheduledTask as ScheduledTask
from tl_ninjarmm.models.scoped_attributes import ScopedAttributes as ScopedAttributes
from tl_ninjarmm.models.scoped_attributes_detailed import ScopedAttributesDetailed as ScopedAttributesDetailed
from tl_ninjarmm.models.scoped_attributes_detailed_report import ScopedAttributesDetailedReport as ScopedAttributesDetailedReport
from tl_ninjarmm.models.scoped_attributes_report import ScopedAttributesReport as ScopedAttributesReport
from tl_ninjarmm.models.script import Script as Script
from tl_ninjarmm.models.script_category import ScriptCategory as ScriptCategory
from tl_ninjarmm.models.script_variable import ScriptVariable as ScriptVariable
from tl_ninjarmm.models.search_default_response import SearchDefaultResponse as SearchDefaultResponse
from tl_ninjarmm.models.search_default_response_devices_inner import SearchDefaultResponseDevicesInner as SearchDefaultResponseDevicesInner
from tl_ninjarmm.models.set_tags_for_asset_request import SetTagsForAssetRequest as SetTagsForAssetRequest
from tl_ninjarmm.models.set_windows_service_configuration_request import SetWindowsServiceConfigurationRequest as SetWindowsServiceConfigurationRequest
from tl_ninjarmm.models.software_patch import SoftwarePatch as SoftwarePatch
from tl_ninjarmm.models.software_patch_report import SoftwarePatchReport as SoftwarePatchReport
from tl_ninjarmm.models.software_product import SoftwareProduct as SoftwareProduct
from tl_ninjarmm.models.software_report import SoftwareReport as SoftwareReport
from tl_ninjarmm.models.sort_by import SortBy as SortBy
from tl_ninjarmm.models.submit_integrity_check_job200_response import SubmitIntegrityCheckJob200Response as SubmitIntegrityCheckJob200Response
from tl_ninjarmm.models.submit_integrity_check_job_request import SubmitIntegrityCheckJobRequest as SubmitIntegrityCheckJobRequest
from tl_ninjarmm.models.technicians_tagged_metadata_dto import TechniciansTaggedMetadataDTO as TechniciansTaggedMetadataDTO
from tl_ninjarmm.models.ticket_board_scrolling_request_dto import TicketBoardScrollingRequestDTO as TicketBoardScrollingRequestDTO
from tl_ninjarmm.models.ticket_dto import TicketDTO as TicketDTO
from tl_ninjarmm.models.ticket_dashboard_public_api_dto import TicketDashboardPublicApiDTO as TicketDashboardPublicApiDTO
from tl_ninjarmm.models.ticket_form_content import TicketFormContent as TicketFormContent
from tl_ninjarmm.models.ticket_form_public_api_dto import TicketFormPublicApiDTO as TicketFormPublicApiDTO
from tl_ninjarmm.models.ticket_log_entry_automation_dto import TicketLogEntryAutomationDTO as TicketLogEntryAutomationDTO
from tl_ninjarmm.models.ticket_log_entry_public_api_dto import TicketLogEntryPublicApiDTO as TicketLogEntryPublicApiDTO
from tl_ninjarmm.models.ticket_metadata import TicketMetadata as TicketMetadata
from tl_ninjarmm.models.ticket_status_public_api_dto import TicketStatusPublicApiDTO as TicketStatusPublicApiDTO
from tl_ninjarmm.models.ticket_time_entry_dto import TicketTimeEntryDTO as TicketTimeEntryDTO
from tl_ninjarmm.models.ticketing_attribute_public_api_dto import TicketingAttributePublicApiDTO as TicketingAttributePublicApiDTO
from tl_ninjarmm.models.ticketing_attribute_value import TicketingAttributeValue as TicketingAttributeValue
from tl_ninjarmm.models.ticketing_board_public_api_dto import TicketingBoardPublicApiDTO as TicketingBoardPublicApiDTO
from tl_ninjarmm.models.timer_settings import TimerSettings as TimerSettings
from tl_ninjarmm.models.update_checklist_template_public_api_request import UpdateChecklistTemplatePublicApiRequest as UpdateChecklistTemplatePublicApiRequest
from tl_ninjarmm.models.update_checklist_templates_request_inner import UpdateChecklistTemplatesRequestInner as UpdateChecklistTemplatesRequestInner
from tl_ninjarmm.models.update_checklist_templates_request_inner_tasks_inner import UpdateChecklistTemplatesRequestInnerTasksInner as UpdateChecklistTemplatesRequestInnerTasksInner
from tl_ninjarmm.models.update_client_checklist_and_tasks_public_api_request import UpdateClientChecklistAndTasksPublicApiRequest as UpdateClientChecklistAndTasksPublicApiRequest
from tl_ninjarmm.models.update_device_maintenance_request import UpdateDeviceMaintenanceRequest as UpdateDeviceMaintenanceRequest
from tl_ninjarmm.models.update_device_request import UpdateDeviceRequest as UpdateDeviceRequest
from tl_ninjarmm.models.update_document_item_public_api_request import UpdateDocumentItemPublicApiRequest as UpdateDocumentItemPublicApiRequest
from tl_ninjarmm.models.update_document_template_public_api_request import UpdateDocumentTemplatePublicApiRequest as UpdateDocumentTemplatePublicApiRequest
from tl_ninjarmm.models.update_document_template_request import UpdateDocumentTemplateRequest as UpdateDocumentTemplateRequest
from tl_ninjarmm.models.update_document_template_request_fields_inner import UpdateDocumentTemplateRequestFieldsInner as UpdateDocumentTemplateRequestFieldsInner
from tl_ninjarmm.models.update_itam_tag_request import UpdateItamTagRequest as UpdateItamTagRequest
from tl_ninjarmm.models.update_knowledge_base_articles_request_inner import UpdateKnowledgeBaseArticlesRequestInner as UpdateKnowledgeBaseArticlesRequestInner
from tl_ninjarmm.models.update_organization_checklists_request_inner import UpdateOrganizationChecklistsRequestInner as UpdateOrganizationChecklistsRequestInner
from tl_ninjarmm.models.update_organization_checklists_request_inner_tasks_inner import UpdateOrganizationChecklistsRequestInnerTasksInner as UpdateOrganizationChecklistsRequestInnerTasksInner
from tl_ninjarmm.models.update_organization_documents200_response_inner import UpdateOrganizationDocuments200ResponseInner as UpdateOrganizationDocuments200ResponseInner
from tl_ninjarmm.models.update_organization_documents_request_inner import UpdateOrganizationDocumentsRequestInner as UpdateOrganizationDocumentsRequestInner
from tl_ninjarmm.models.update_organization_request import UpdateOrganizationRequest as UpdateOrganizationRequest
from tl_ninjarmm.models.update_request import UpdateRequest as UpdateRequest
from tl_ninjarmm.models.update_tag_request import UpdateTagRequest as UpdateTagRequest
from tl_ninjarmm.models.update_ticket import UpdateTicket as UpdateTicket
from tl_ninjarmm.models.upload_temp_attachments200_response_inner import UploadTempAttachments200ResponseInner as UploadTempAttachments200ResponseInner
from tl_ninjarmm.models.upload_temp_attachments_request_files_inner import UploadTempAttachmentsRequestFilesInner as UploadTempAttachmentsRequestFilesInner
from tl_ninjarmm.models.upload_temp_attachments_request_files_inner_content_disposition import UploadTempAttachmentsRequestFilesInnerContentDisposition as UploadTempAttachmentsRequestFilesInnerContentDisposition
from tl_ninjarmm.models.upload_temp_attachments_request_files_inner_form_data_content_disposition import UploadTempAttachmentsRequestFilesInnerFormDataContentDisposition as UploadTempAttachmentsRequestFilesInnerFormDataContentDisposition
from tl_ninjarmm.models.upload_temp_attachments_request_files_inner_media_type import UploadTempAttachmentsRequestFilesInnerMediaType as UploadTempAttachmentsRequestFilesInnerMediaType
from tl_ninjarmm.models.upload_temp_attachments_request_files_inner_parent import UploadTempAttachmentsRequestFilesInnerParent as UploadTempAttachmentsRequestFilesInnerParent
from tl_ninjarmm.models.upload_temp_attachments_request_files_inner_parent_parameterized_headers_value_inner import UploadTempAttachmentsRequestFilesInnerParentParameterizedHeadersValueInner as UploadTempAttachmentsRequestFilesInnerParentParameterizedHeadersValueInner
from tl_ninjarmm.models.user import User as User
from tl_ninjarmm.models.user_basic_info import UserBasicInfo as UserBasicInfo
from tl_ninjarmm.models.vm_guest import VMGuest as VMGuest
from tl_ninjarmm.models.vm_host import VMHost as VMHost
from tl_ninjarmm.models.volume import Volume as Volume
from tl_ninjarmm.models.volume_bit_locker_status import VolumeBitLockerStatus as VolumeBitLockerStatus
from tl_ninjarmm.models.volumes_report import VolumesReport as VolumesReport
from tl_ninjarmm.models.warranty_dates import WarrantyDates as WarrantyDates
from tl_ninjarmm.models.webhook_configuration import WebhookConfiguration as WebhookConfiguration
from tl_ninjarmm.models.windows_event_policy_condition_create_request import WindowsEventPolicyConditionCreateRequest as WindowsEventPolicyConditionCreateRequest
from tl_ninjarmm.models.windows_event_policy_condition_occurrence import WindowsEventPolicyConditionOccurrence as WindowsEventPolicyConditionOccurrence
from tl_ninjarmm.models.windows_event_policy_condition_response import WindowsEventPolicyConditionResponse as WindowsEventPolicyConditionResponse
from tl_ninjarmm.models.windows_event_policy_condition_text import WindowsEventPolicyConditionText as WindowsEventPolicyConditionText
from tl_ninjarmm.models.windows_service import WindowsService as WindowsService
from tl_ninjarmm.models.windows_service_configuration import WindowsServiceConfiguration as WindowsServiceConfiguration
from tl_ninjarmm.models.windows_service_control_request import WindowsServiceControlRequest as WindowsServiceControlRequest
from tl_ninjarmm.models.windows_service_report import WindowsServiceReport as WindowsServiceReport
