# coding: utf-8

# flake8: noqa

"""
    NinjaOne Public API 2.0

    NinjaOne Public API documentation.

    The version of the OpenAPI document: 2.0.9-draft
    Contact: api@ninjarmm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DevicesApi",
    "ManagementApi",
    "SystemApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ActivitiesResponse",
    "Activity",
    "Alert",
    "Application",
    "AttributeContent",
    "AttributeContentAdvancedSettings",
    "AttributeContentAdvancedSettingsComplexityRules",
    "AttributeContentAdvancedSettingsDateFilters",
    "AttributeContentAdvancedSettingsNumericRange",
    "AttributeContentValue",
    "AttributePublicApiDTO",
    "AutomationScript",
    "BackupUsage",
    "Contact",
    "ContactPatchRequest",
    "CreateContactRequest",
    "CreateEndUserRequest",
    "CreateTechnicianRequest",
    "CredentialReference",
    "CustomFieldPolicyConditionResponse",
    "CustomFieldsPolicyConditionCreateRequest",
    "Device",
    "DeviceCredentialOptions",
    "DeviceIDList",
    "DeviceLink",
    "DeviceMutableProperties",
    "DeviceScriptingOptions",
    "DeviceSearchMatch",
    "DeviceSearchResults",
    "DiskDrive",
    "EndUser",
    "EndUserCustomization",
    "EndUserPatchRequest",
    "FeatureSettings",
    "GenerateInstallerRequestDto",
    "Group",
    "InstallerContent",
    "Job",
    "Link",
    "Location",
    "LocationModel",
    "LocationWithOrganizationRef",
    "LoggedOnUser",
    "Maintenance",
    "MaintenanceSettings",
    "NetworkInterface",
    "NodeActivitiesResponse",
    "NodeReferences",
    "NodeRole",
    "NodeRolePolicyAssignment",
    "NodeWithDetailedReferences",
    "Note",
    "NotificationChannel",
    "OSPatch",
    "Organization",
    "OrganizationDetailed",
    "OrganizationModel",
    "OrganizationSettings",
    "OrganizationWithLocationsAndPolicyAssignmentsModel",
    "Policy",
    "PolicyConditionCustomField",
    "PolicyConditionInheritanceStatus",
    "PolicyConditionScript",
    "PolicyConditionScriptVariable",
    "PolicyInfo",
    "PolicyOverrides",
    "Processor",
    "RebootRequest",
    "RoleMember",
    "RunScriptRequest",
    "ScheduledTask",
    "Script",
    "ScriptCategory",
    "ScriptVariable",
    "SoftwarePatch",
    "SoftwareProduct",
    "Technician",
    "UpdateTechnicianRequest",
    "User",
    "UserRole",
    "Volume",
    "VolumeBitLockerStatus",
    "WarrantyDates",
    "WindowsEventPolicyConditionCreateRequest",
    "WindowsEventPolicyConditionOccurrence",
    "WindowsEventPolicyConditionResponse",
    "WindowsEventPolicyConditionText",
    "WindowsService",
    "WindowsServiceConfiguration",
    "WindowsServiceControlRequest",
]

# import apis into sdk package
from tl_ninjarmm.api.devices_api import DevicesApi as DevicesApi
from tl_ninjarmm.api.management_api import ManagementApi as ManagementApi
from tl_ninjarmm.api.system_api import SystemApi as SystemApi

# import ApiClient
from tl_ninjarmm.api_response import ApiResponse as ApiResponse
from tl_ninjarmm.api_client import ApiClient as ApiClient
from tl_ninjarmm.configuration import Configuration as Configuration
from tl_ninjarmm.exceptions import OpenApiException as OpenApiException
from tl_ninjarmm.exceptions import ApiTypeError as ApiTypeError
from tl_ninjarmm.exceptions import ApiValueError as ApiValueError
from tl_ninjarmm.exceptions import ApiKeyError as ApiKeyError
from tl_ninjarmm.exceptions import ApiAttributeError as ApiAttributeError
from tl_ninjarmm.exceptions import ApiException as ApiException

# import models into sdk package
from tl_ninjarmm.models.activities_response import ActivitiesResponse as ActivitiesResponse
from tl_ninjarmm.models.activity import Activity as Activity
from tl_ninjarmm.models.alert import Alert as Alert
from tl_ninjarmm.models.application import Application as Application
from tl_ninjarmm.models.attribute_content import AttributeContent as AttributeContent
from tl_ninjarmm.models.attribute_content_advanced_settings import AttributeContentAdvancedSettings as AttributeContentAdvancedSettings
from tl_ninjarmm.models.attribute_content_advanced_settings_complexity_rules import AttributeContentAdvancedSettingsComplexityRules as AttributeContentAdvancedSettingsComplexityRules
from tl_ninjarmm.models.attribute_content_advanced_settings_date_filters import AttributeContentAdvancedSettingsDateFilters as AttributeContentAdvancedSettingsDateFilters
from tl_ninjarmm.models.attribute_content_advanced_settings_numeric_range import AttributeContentAdvancedSettingsNumericRange as AttributeContentAdvancedSettingsNumericRange
from tl_ninjarmm.models.attribute_content_value import AttributeContentValue as AttributeContentValue
from tl_ninjarmm.models.attribute_public_api_dto import AttributePublicApiDTO as AttributePublicApiDTO
from tl_ninjarmm.models.automation_script import AutomationScript as AutomationScript
from tl_ninjarmm.models.backup_usage import BackupUsage as BackupUsage
from tl_ninjarmm.models.contact import Contact as Contact
from tl_ninjarmm.models.contact_patch_request import ContactPatchRequest as ContactPatchRequest
from tl_ninjarmm.models.create_contact_request import CreateContactRequest as CreateContactRequest
from tl_ninjarmm.models.create_end_user_request import CreateEndUserRequest as CreateEndUserRequest
from tl_ninjarmm.models.create_technician_request import CreateTechnicianRequest as CreateTechnicianRequest
from tl_ninjarmm.models.credential_reference import CredentialReference as CredentialReference
from tl_ninjarmm.models.custom_field_policy_condition_response import CustomFieldPolicyConditionResponse as CustomFieldPolicyConditionResponse
from tl_ninjarmm.models.custom_fields_policy_condition_create_request import CustomFieldsPolicyConditionCreateRequest as CustomFieldsPolicyConditionCreateRequest
from tl_ninjarmm.models.device import Device as Device
from tl_ninjarmm.models.device_credential_options import DeviceCredentialOptions as DeviceCredentialOptions
from tl_ninjarmm.models.device_id_list import DeviceIDList as DeviceIDList
from tl_ninjarmm.models.device_link import DeviceLink as DeviceLink
from tl_ninjarmm.models.device_mutable_properties import DeviceMutableProperties as DeviceMutableProperties
from tl_ninjarmm.models.device_scripting_options import DeviceScriptingOptions as DeviceScriptingOptions
from tl_ninjarmm.models.device_search_match import DeviceSearchMatch as DeviceSearchMatch
from tl_ninjarmm.models.device_search_results import DeviceSearchResults as DeviceSearchResults
from tl_ninjarmm.models.disk_drive import DiskDrive as DiskDrive
from tl_ninjarmm.models.end_user import EndUser as EndUser
from tl_ninjarmm.models.end_user_customization import EndUserCustomization as EndUserCustomization
from tl_ninjarmm.models.end_user_patch_request import EndUserPatchRequest as EndUserPatchRequest
from tl_ninjarmm.models.feature_settings import FeatureSettings as FeatureSettings
from tl_ninjarmm.models.generate_installer_request_dto import GenerateInstallerRequestDto as GenerateInstallerRequestDto
from tl_ninjarmm.models.group import Group as Group
from tl_ninjarmm.models.installer_content import InstallerContent as InstallerContent
from tl_ninjarmm.models.job import Job as Job
from tl_ninjarmm.models.link import Link as Link
from tl_ninjarmm.models.location import Location as Location
from tl_ninjarmm.models.location_model import LocationModel as LocationModel
from tl_ninjarmm.models.location_with_organization_ref import LocationWithOrganizationRef as LocationWithOrganizationRef
from tl_ninjarmm.models.logged_on_user import LoggedOnUser as LoggedOnUser
from tl_ninjarmm.models.maintenance import Maintenance as Maintenance
from tl_ninjarmm.models.maintenance_settings import MaintenanceSettings as MaintenanceSettings
from tl_ninjarmm.models.network_interface import NetworkInterface as NetworkInterface
from tl_ninjarmm.models.node_activities_response import NodeActivitiesResponse as NodeActivitiesResponse
from tl_ninjarmm.models.node_references import NodeReferences as NodeReferences
from tl_ninjarmm.models.node_role import NodeRole as NodeRole
from tl_ninjarmm.models.node_role_policy_assignment import NodeRolePolicyAssignment as NodeRolePolicyAssignment
from tl_ninjarmm.models.node_with_detailed_references import NodeWithDetailedReferences as NodeWithDetailedReferences
from tl_ninjarmm.models.note import Note as Note
from tl_ninjarmm.models.notification_channel import NotificationChannel as NotificationChannel
from tl_ninjarmm.models.os_patch import OSPatch as OSPatch
from tl_ninjarmm.models.organization import Organization as Organization
from tl_ninjarmm.models.organization_detailed import OrganizationDetailed as OrganizationDetailed
from tl_ninjarmm.models.organization_model import OrganizationModel as OrganizationModel
from tl_ninjarmm.models.organization_settings import OrganizationSettings as OrganizationSettings
from tl_ninjarmm.models.organization_with_locations_and_policy_assignments_model import OrganizationWithLocationsAndPolicyAssignmentsModel as OrganizationWithLocationsAndPolicyAssignmentsModel
from tl_ninjarmm.models.policy import Policy as Policy
from tl_ninjarmm.models.policy_condition_custom_field import PolicyConditionCustomField as PolicyConditionCustomField
from tl_ninjarmm.models.policy_condition_inheritance_status import PolicyConditionInheritanceStatus as PolicyConditionInheritanceStatus
from tl_ninjarmm.models.policy_condition_script import PolicyConditionScript as PolicyConditionScript
from tl_ninjarmm.models.policy_condition_script_variable import PolicyConditionScriptVariable as PolicyConditionScriptVariable
from tl_ninjarmm.models.policy_info import PolicyInfo as PolicyInfo
from tl_ninjarmm.models.policy_overrides import PolicyOverrides as PolicyOverrides
from tl_ninjarmm.models.processor import Processor as Processor
from tl_ninjarmm.models.reboot_request import RebootRequest as RebootRequest
from tl_ninjarmm.models.role_member import RoleMember as RoleMember
from tl_ninjarmm.models.run_script_request import RunScriptRequest as RunScriptRequest
from tl_ninjarmm.models.scheduled_task import ScheduledTask as ScheduledTask
from tl_ninjarmm.models.script import Script as Script
from tl_ninjarmm.models.script_category import ScriptCategory as ScriptCategory
from tl_ninjarmm.models.script_variable import ScriptVariable as ScriptVariable
from tl_ninjarmm.models.software_patch import SoftwarePatch as SoftwarePatch
from tl_ninjarmm.models.software_product import SoftwareProduct as SoftwareProduct
from tl_ninjarmm.models.technician import Technician as Technician
from tl_ninjarmm.models.update_technician_request import UpdateTechnicianRequest as UpdateTechnicianRequest
from tl_ninjarmm.models.user import User as User
from tl_ninjarmm.models.user_role import UserRole as UserRole
from tl_ninjarmm.models.volume import Volume as Volume
from tl_ninjarmm.models.volume_bit_locker_status import VolumeBitLockerStatus as VolumeBitLockerStatus
from tl_ninjarmm.models.warranty_dates import WarrantyDates as WarrantyDates
from tl_ninjarmm.models.windows_event_policy_condition_create_request import WindowsEventPolicyConditionCreateRequest as WindowsEventPolicyConditionCreateRequest
from tl_ninjarmm.models.windows_event_policy_condition_occurrence import WindowsEventPolicyConditionOccurrence as WindowsEventPolicyConditionOccurrence
from tl_ninjarmm.models.windows_event_policy_condition_response import WindowsEventPolicyConditionResponse as WindowsEventPolicyConditionResponse
from tl_ninjarmm.models.windows_event_policy_condition_text import WindowsEventPolicyConditionText as WindowsEventPolicyConditionText
from tl_ninjarmm.models.windows_service import WindowsService as WindowsService
from tl_ninjarmm.models.windows_service_configuration import WindowsServiceConfiguration as WindowsServiceConfiguration
from tl_ninjarmm.models.windows_service_control_request import WindowsServiceControlRequest as WindowsServiceControlRequest
