# coding: utf-8

"""
NinjaOne Public API 2.0

NinjaOne Public API documentation.

The version of the OpenAPI document: 2.0.9-draft
Contact: api@ninjarmm.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictFloat,
    StrictInt,
    StrictStr,
    field_validator,
)
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Set
from typing_extensions import Self


class Activity(BaseModel):
    """
    Activity
    """  # noqa: E501

    id: Optional[StrictInt] = Field(default=None, description="Activity identifier")
    activity_time: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, description="Activity timestamp", alias="activityTime"
    )
    device_id: Optional[StrictInt] = Field(
        default=None, description="Device identifier", alias="deviceId"
    )
    severity: Optional[StrictStr] = Field(default=None, description="Severity")
    priority: Optional[StrictStr] = Field(default=None, description="Priority")
    series_uid: Optional[StrictStr] = Field(
        default=None,
        description="Activity series UID (job/condition UID)",
        alias="seriesUid",
    )
    activity_type: Optional[StrictStr] = Field(
        default=None, description="Activity type code", alias="activityType"
    )
    status_code: Optional[StrictStr] = Field(
        default=None, description="Activity status code", alias="statusCode"
    )
    status: Optional[StrictStr] = Field(default=None, description="Status description")
    activity_result: Optional[StrictStr] = Field(
        default=None, description="Activity result", alias="activityResult"
    )
    source_config_uid: Optional[StrictStr] = Field(
        default=None,
        description="Source configuration/policy element reference",
        alias="sourceConfigUid",
    )
    source_name: Optional[StrictStr] = Field(
        default=None,
        description="Source configuration/policy element name",
        alias="sourceName",
    )
    subject: Optional[StrictStr] = Field(default=None, description="Activity subject")
    user_id: Optional[StrictInt] = Field(
        default=None, description="User identifier", alias="userId"
    )
    message: Optional[StrictStr] = Field(default=None, description="Activity message")
    type: Optional[StrictStr] = Field(
        default=None, description="Activity type description"
    )
    data: Optional[Dict[str, Any]] = Field(default=None, description="Activity data")
    __properties: ClassVar[List[str]] = [
        "id",
        "activityTime",
        "deviceId",
        "severity",
        "priority",
        "seriesUid",
        "activityType",
        "statusCode",
        "status",
        "activityResult",
        "sourceConfigUid",
        "sourceName",
        "subject",
        "userId",
        "message",
        "type",
        "data",
    ]

    @field_validator("severity")
    def severity_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["NONE", "MINOR", "MODERATE", "MAJOR", "CRITICAL"]):
            raise ValueError(
                "must be one of enum values ('NONE', 'MINOR', 'MODERATE', 'MAJOR', 'CRITICAL')"
            )
        return value

    @field_validator("priority")
    def priority_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["NONE", "LOW", "MEDIUM", "HIGH"]):
            raise ValueError(
                "must be one of enum values ('NONE', 'LOW', 'MEDIUM', 'HIGH')"
            )
        return value

    @field_validator("activity_result")
    def activity_result_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["SUCCESS", "FAILURE", "UNSUPPORTED", "UNCOMPLETED"]):
            raise ValueError(
                "must be one of enum values ('SUCCESS', 'FAILURE', 'UNSUPPORTED', 'UNCOMPLETED')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Activity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Activity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "activityTime": obj.get("activityTime"),
                "deviceId": obj.get("deviceId"),
                "severity": obj.get("severity"),
                "priority": obj.get("priority"),
                "seriesUid": obj.get("seriesUid"),
                "activityType": obj.get("activityType"),
                "statusCode": obj.get("statusCode"),
                "status": obj.get("status"),
                "activityResult": obj.get("activityResult"),
                "sourceConfigUid": obj.get("sourceConfigUid"),
                "sourceName": obj.get("sourceName"),
                "subject": obj.get("subject"),
                "userId": obj.get("userId"),
                "message": obj.get("message"),
                "type": obj.get("type"),
                "data": obj.get("data"),
            }
        )
        return _obj
