# coding: utf-8

"""
NinjaOne Public API 2.0

NinjaOne Public API documentation.

The version of the OpenAPI document: 2.0.9-draft
Contact: api@ninjarmm.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictFloat,
    StrictInt,
    StrictStr,
    field_validator,
)
from typing import Any, ClassVar, Dict, List, Optional, Union
from tl_ninjarmm.models.attribute_content_public_api_dto import (
    AttributeContentPublicApiDTO,
)
from typing import Set
from typing_extensions import Self


class AttributeFormContentCommonItemPublicApiDTO(BaseModel):
    """
    This object represents either an attribute, or a UI Element. The available attributes will depend on which type it is
    """  # noqa: E501

    id: Optional[StrictInt] = Field(default=None, description="ID of an attribute")
    name: Optional[StrictStr] = Field(
        default=None, description="Name of the content item"
    )
    field_name: Optional[StrictStr] = Field(
        default=None, description="Field name of the attribute", alias="fieldName"
    )
    description: Optional[StrictStr] = Field(
        default=None, description="Description of the content item"
    )
    entity_type: Optional[StrictStr] = Field(
        default=None,
        description="If the attribute references a specific entity, its type will be specified in this field",
        alias="entityType",
    )
    attribute_type: Optional[StrictStr] = Field(
        default=None, description="Type of the attribute", alias="attributeType"
    )
    attribute_scope: Optional[StrictStr] = Field(
        default=None,
        description="Scope of the attribute. NOTE: This field is being depricated",
        alias="attributeScope",
    )
    definition_scope: Optional[List[StrictStr]] = Field(
        default=None,
        description="Definition scopes of the attribute",
        alias="definitionScope",
    )
    technician_permission: Optional[StrictStr] = Field(
        default=None,
        description="Type of technician permission on the attribute",
        alias="technicianPermission",
    )
    script_permission: Optional[StrictStr] = Field(
        default=None,
        description="Type of script permission on the attribute",
        alias="scriptPermission",
    )
    api_permission: Optional[StrictStr] = Field(
        default=None,
        description="Type of API permission on the attribute",
        alias="apiPermission",
    )
    default_value: Optional[StrictStr] = Field(
        default=None,
        description="For multi-select attributes, this is the id of the default value",
        alias="defaultValue",
    )
    content: Optional[AttributeContentPublicApiDTO] = None
    active: Optional[StrictBool] = Field(
        default=None, description="Whether the attribute is active or not"
    )
    create_time: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="The time that the attribute was created (unix epoch)",
        alias="createTime",
    )
    update_time: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="The time that the attribute was last updated (unix epoch)",
        alias="updateTime",
    )
    ui_element_uid: Optional[StrictStr] = Field(
        default=None,
        description="For UI elements, the uuid of the element",
        alias="uiElementUid",
    )
    ui_element_type: Optional[StrictStr] = Field(
        default=None,
        description="For UI elements, type of the element",
        alias="uiElementType",
    )
    ui_element_value: Optional[StrictStr] = Field(
        default=None,
        description="For UI elements, value of the element",
        alias="uiElementValue",
    )
    ui_element_create_time: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="For UI elements, timestamp of when the element was created (unix epoch)",
        alias="uiElementCreateTime",
    )
    ui_element_update_time: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="For UI elements, timestamp of when the element was last updated (unix epoch)",
        alias="uiElementUpdateTime",
    )
    __properties: ClassVar[List[str]] = [
        "id",
        "name",
        "fieldName",
        "description",
        "entityType",
        "attributeType",
        "attributeScope",
        "definitionScope",
        "technicianPermission",
        "scriptPermission",
        "apiPermission",
        "defaultValue",
        "content",
        "active",
        "createTime",
        "updateTime",
        "uiElementUid",
        "uiElementType",
        "uiElementValue",
        "uiElementCreateTime",
        "uiElementUpdateTime",
    ]

    @field_validator("entity_type")
    def entity_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["USER", "NODE", "TICKET", "DOCUMENT"]):
            raise ValueError(
                "must be one of enum values ('USER', 'NODE', 'TICKET', 'DOCUMENT')"
            )
        return value

    @field_validator("attribute_type")
    def attribute_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(
            [
                "DROPDOWN",
                "MULTI_SELECT",
                "CHECKBOX",
                "TEXT",
                "TEXT_MULTILINE",
                "TEXT_ENCRYPTED",
                "NUMERIC",
                "DECIMAL",
                "DATE",
                "DATE_TIME",
                "TIME",
                "ATTACHMENT",
                "NODE_DROPDOWN",
                "NODE_MULTI_SELECT",
                "CLIENT_DROPDOWN",
                "CLIENT_MULTI_SELECT",
                "CLIENT_LOCATION_DROPDOWN",
                "CLIENT_LOCATION_MULTI_SELECT",
                "CLIENT_DOCUMENT_DROPDOWN",
                "CLIENT_DOCUMENT_MULTI_SELECT",
                "EMAIL",
                "PHONE",
                "IP_ADDRESS",
                "WYSIWYG",
                "URL",
            ]
        ):
            raise ValueError(
                "must be one of enum values ('DROPDOWN', 'MULTI_SELECT', 'CHECKBOX', 'TEXT', 'TEXT_MULTILINE', 'TEXT_ENCRYPTED', 'NUMERIC', 'DECIMAL', 'DATE', 'DATE_TIME', 'TIME', 'ATTACHMENT', 'NODE_DROPDOWN', 'NODE_MULTI_SELECT', 'CLIENT_DROPDOWN', 'CLIENT_MULTI_SELECT', 'CLIENT_LOCATION_DROPDOWN', 'CLIENT_LOCATION_MULTI_SELECT', 'CLIENT_DOCUMENT_DROPDOWN', 'CLIENT_DOCUMENT_MULTI_SELECT', 'EMAIL', 'PHONE', 'IP_ADDRESS', 'WYSIWYG', 'URL')"
            )
        return value

    @field_validator("attribute_scope")
    def attribute_scope_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["NODE_GLOBAL", "NODE_ROLE", "NODE_CLASS"]):
            raise ValueError(
                "must be one of enum values ('NODE_GLOBAL', 'NODE_ROLE', 'NODE_CLASS')"
            )
        return value

    @field_validator("definition_scope")
    def definition_scope_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(["NODE", "END_USER", "LOCATION", "ORGANIZATION"]):
                raise ValueError(
                    "each list item must be one of ('NODE', 'END_USER', 'LOCATION', 'ORGANIZATION')"
                )
        return value

    @field_validator("technician_permission")
    def technician_permission_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["NONE", "EDITABLE", "READ_ONLY"]):
            raise ValueError(
                "must be one of enum values ('NONE', 'EDITABLE', 'READ_ONLY')"
            )
        return value

    @field_validator("script_permission")
    def script_permission_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["NONE", "READ_ONLY", "WRITE_ONLY", "READ_WRITE"]):
            raise ValueError(
                "must be one of enum values ('NONE', 'READ_ONLY', 'WRITE_ONLY', 'READ_WRITE')"
            )
        return value

    @field_validator("api_permission")
    def api_permission_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["NONE", "READ_ONLY", "WRITE_ONLY", "READ_WRITE"]):
            raise ValueError(
                "must be one of enum values ('NONE', 'READ_ONLY', 'WRITE_ONLY', 'READ_WRITE')"
            )
        return value

    @field_validator("ui_element_type")
    def ui_element_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["TITLE", "DESCRIPTION", "SEPARATOR"]):
            raise ValueError(
                "must be one of enum values ('TITLE', 'DESCRIPTION', 'SEPARATOR')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AttributeFormContentCommonItemPublicApiDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of content
        if self.content:
            _dict["content"] = self.content.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AttributeFormContentCommonItemPublicApiDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "name": obj.get("name"),
                "fieldName": obj.get("fieldName"),
                "description": obj.get("description"),
                "entityType": obj.get("entityType"),
                "attributeType": obj.get("attributeType"),
                "attributeScope": obj.get("attributeScope"),
                "definitionScope": obj.get("definitionScope"),
                "technicianPermission": obj.get("technicianPermission"),
                "scriptPermission": obj.get("scriptPermission"),
                "apiPermission": obj.get("apiPermission"),
                "defaultValue": obj.get("defaultValue"),
                "content": AttributeContentPublicApiDTO.from_dict(obj["content"])
                if obj.get("content") is not None
                else None,
                "active": obj.get("active"),
                "createTime": obj.get("createTime"),
                "updateTime": obj.get("updateTime"),
                "uiElementUid": obj.get("uiElementUid"),
                "uiElementType": obj.get("uiElementType"),
                "uiElementValue": obj.get("uiElementValue"),
                "uiElementCreateTime": obj.get("uiElementCreateTime"),
                "uiElementUpdateTime": obj.get("uiElementUpdateTime"),
            }
        )
        return _obj
