# coding: utf-8

"""
    NinjaOne Public API 2.0

    Ninja One Public API documentation. <br><br> See also: <br>  <a href=\"https://resources.ninjarmm.com/API/Ninja+RMM+Public+API+v2.0.5+Device+Filter+Syntax.pdf\">Device Filter syntax</a><br> <a href=\"https://resources.ninjarmm.com/API/Ninja+RMM+Public+API+v2.0.5+Webhooks.pdf\">Webhooks</a>

    The version of the OpenAPI document: 2.0.9-draft
    Contact: api@ninjarmm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from tl_ninjarmm.models.get_custom_fields_policy_conditions_default_response_inner_scripts_inner import GetCustomFieldsPolicyConditionsDefaultResponseInnerScriptsInner
from tl_ninjarmm.models.get_windows_event_policy_conditions_default_response_inner_occurrence import GetWindowsEventPolicyConditionsDefaultResponseInnerOccurrence
from tl_ninjarmm.models.get_windows_event_policy_conditions_default_response_inner_text import GetWindowsEventPolicyConditionsDefaultResponseInnerText
from typing import Optional, Set
from typing_extensions import Self

class CreateWindowsEventPolicyConditionRequest(BaseModel):
    """
    Windows event policy condition create request payload
    """ # noqa: E501
    enabled: Optional[StrictBool] = Field(default=True, description="Policy condition enabled")
    display_name: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=255)]] = Field(default=None, description="Policy condition display name", alias="displayName")
    severity: Optional[StrictStr] = Field(default='NONE', description="Policy condition severity")
    priority: Optional[StrictStr] = Field(default='NONE', description="Policy condition priority")
    channels: Optional[Annotated[List[StrictInt], Field(min_length=0, max_length=20)]] = Field(default=None, description="Policy condition notification channels")
    scripts: Optional[Annotated[List[GetCustomFieldsPolicyConditionsDefaultResponseInnerScriptsInner], Field(min_length=0, max_length=20)]] = Field(default=None, description="Policy condition scripts")
    notification_action: Optional[StrictStr] = Field(default='NONE', description="Policy condition notification action", alias="notificationAction")
    notify_on_reset: Optional[StrictBool] = Field(default=False, description="Policy condition notify on reset", alias="notifyOnReset")
    reset_threshold: Optional[StrictInt] = Field(default=14400, description="Policy condition reset threshold (seconds)", alias="resetThreshold")
    source: Annotated[str, Field(min_length=0, strict=True, max_length=255)] = Field(description="Event Source")
    event_ids: Annotated[List[StrictInt], Field(min_length=0, max_length=20)] = Field(description="Event IDs", alias="eventIds")
    text: Optional[GetWindowsEventPolicyConditionsDefaultResponseInnerText] = None
    occurrence: Optional[GetWindowsEventPolicyConditionsDefaultResponseInnerOccurrence] = None
    __properties: ClassVar[List[str]] = ["enabled", "displayName", "severity", "priority", "channels", "scripts", "notificationAction", "notifyOnReset", "resetThreshold", "source", "eventIds", "text", "occurrence"]

    @field_validator('severity')
    def severity_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NONE', 'MINOR', 'MODERATE', 'MAJOR', 'CRITICAL']):
            raise ValueError("must be one of enum values ('NONE', 'MINOR', 'MODERATE', 'MAJOR', 'CRITICAL')")
        return value

    @field_validator('priority')
    def priority_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NONE', 'LOW', 'MEDIUM', 'HIGH']):
            raise ValueError("must be one of enum values ('NONE', 'LOW', 'MEDIUM', 'HIGH')")
        return value

    @field_validator('notification_action')
    def notification_action_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NONE', 'SEND']):
            raise ValueError("must be one of enum values ('NONE', 'SEND')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateWindowsEventPolicyConditionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in scripts (list)
        _items = []
        if self.scripts:
            for _item_scripts in self.scripts:
                if _item_scripts:
                    _items.append(_item_scripts.to_dict())
            _dict['scripts'] = _items
        # override the default output from pydantic by calling `to_dict()` of text
        if self.text:
            _dict['text'] = self.text.to_dict()
        # override the default output from pydantic by calling `to_dict()` of occurrence
        if self.occurrence:
            _dict['occurrence'] = self.occurrence.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateWindowsEventPolicyConditionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else True,
            "displayName": obj.get("displayName"),
            "severity": obj.get("severity") if obj.get("severity") is not None else 'NONE',
            "priority": obj.get("priority") if obj.get("priority") is not None else 'NONE',
            "channels": obj.get("channels"),
            "scripts": [GetCustomFieldsPolicyConditionsDefaultResponseInnerScriptsInner.from_dict(_item) for _item in obj["scripts"]] if obj.get("scripts") is not None else None,
            "notificationAction": obj.get("notificationAction") if obj.get("notificationAction") is not None else 'NONE',
            "notifyOnReset": obj.get("notifyOnReset") if obj.get("notifyOnReset") is not None else False,
            "resetThreshold": obj.get("resetThreshold") if obj.get("resetThreshold") is not None else 14400,
            "source": obj.get("source"),
            "eventIds": obj.get("eventIds"),
            "text": GetWindowsEventPolicyConditionsDefaultResponseInnerText.from_dict(obj["text"]) if obj.get("text") is not None else None,
            "occurrence": GetWindowsEventPolicyConditionsDefaultResponseInnerOccurrence.from_dict(obj["occurrence"]) if obj.get("occurrence") is not None else None
        })
        return _obj


