# coding: utf-8

"""
    NinjaOne Public API 2.0

    Ninja One Public API documentation. <br><br> See also: <br>  <a href=\"https://resources.ninjarmm.com/API/Ninja+RMM+Public+API+v2.0.5+Device+Filter+Syntax.pdf\">Device Filter syntax</a><br> <a href=\"https://resources.ninjarmm.com/API/Ninja+RMM+Public+API+v2.0.5+Webhooks.pdf\">Webhooks</a>

    The version of the OpenAPI document: 2.0.9-draft
    Contact: api@ninjarmm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from tl_ninjarmm.models.archive_checklist_template200_response_inner_description import ArchiveChecklistTemplate200ResponseInnerDescription
from tl_ninjarmm.models.update_organization_checklists_request_inner_tasks_inner import UpdateOrganizationChecklistsRequestInnerTasksInner
from typing import Optional, Set
from typing_extensions import Self

class CreateOrganizationChecklistsRequestInner(BaseModel):
    """
    CreateOrganizationChecklistsRequestInner
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="Checklist name")
    description: Optional[ArchiveChecklistTemplate200ResponseInnerDescription] = None
    required: Optional[StrictBool] = Field(default=None, description="Indicates if the checklist completion is required")
    due_date: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Due date", alias="dueDate")
    assigned_to_user_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="User identifier assigned to the checklist", alias="assignedToUserId")
    organization_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Organization identifier", alias="organizationId")
    checklist_template_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Checklist template identifier", alias="checklistTemplateId")
    tasks: Optional[List[UpdateOrganizationChecklistsRequestInnerTasksInner]] = Field(default=None, description="Checklist tasks")
    __properties: ClassVar[List[str]] = ["name", "description", "required", "dueDate", "assignedToUserId", "organizationId", "checklistTemplateId", "tasks"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateOrganizationChecklistsRequestInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of description
        if self.description:
            _dict['description'] = self.description.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tasks (list)
        _items = []
        if self.tasks:
            for _item_tasks in self.tasks:
                if _item_tasks:
                    _items.append(_item_tasks.to_dict())
            _dict['tasks'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateOrganizationChecklistsRequestInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": ArchiveChecklistTemplate200ResponseInnerDescription.from_dict(obj["description"]) if obj.get("description") is not None else None,
            "required": obj.get("required"),
            "dueDate": obj.get("dueDate"),
            "assignedToUserId": obj.get("assignedToUserId"),
            "organizationId": obj.get("organizationId"),
            "checklistTemplateId": obj.get("checklistTemplateId"),
            "tasks": [UpdateOrganizationChecklistsRequestInnerTasksInner.from_dict(_item) for _item in obj["tasks"]] if obj.get("tasks") is not None else None
        })
        return _obj


