# coding: utf-8

"""
NinjaOne Public API 2.0

NinjaOne Public API documentation.

The version of the OpenAPI document: 2.0.9-draft
Contact: api@ninjarmm.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class CustomTabLabelPublicApiDTO(BaseModel):
    """
    Simplified view of a tab that omits the content of the tab. Used when retrieving tab summaries/lists
    """  # noqa: E501

    id: Optional[StrictInt] = Field(default=None, description="Tab ID")
    name: Optional[StrictStr] = Field(default=None, description="Display name of tab")
    node_role_id: Optional[StrictInt] = Field(
        default=None,
        description="For tabs associated with a role, this will be the roleId the tab is associated with",
        alias="nodeRoleId",
    )
    position: Optional[StrictInt] = Field(
        default=None,
        description="When tabs are ordered, such as when retrieving a tab summary, this is the position that the tab should be rendered in",
    )
    hidden_for_roles: Optional[List[StrictInt]] = Field(
        default=None,
        description="Array of roleIds that should not display this custom tab",
        alias="hiddenForRoles",
    )
    default: Optional[StrictBool] = Field(
        default=None, description="True if this tab is a 'default tab'"
    )
    __properties: ClassVar[List[str]] = [
        "id",
        "name",
        "nodeRoleId",
        "position",
        "hiddenForRoles",
        "default",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomTabLabelPublicApiDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomTabLabelPublicApiDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "name": obj.get("name"),
                "nodeRoleId": obj.get("nodeRoleId"),
                "position": obj.get("position"),
                "hiddenForRoles": obj.get("hiddenForRoles"),
                "default": obj.get("default"),
            }
        )
        return _obj
