# coding: utf-8

"""
    NinjaOne Public API 2.0

    Ninja One Public API documentation. <br><br> See also: <br>  <a href=\"https://resources.ninjarmm.com/API/Ninja+RMM+Public+API+v2.0.5+Device+Filter+Syntax.pdf\">Device Filter syntax</a><br> <a href=\"https://resources.ninjarmm.com/API/Ninja+RMM+Public+API+v2.0.5+Webhooks.pdf\">Webhooks</a>

    The version of the OpenAPI document: 2.0.9-draft
    Contact: api@ninjarmm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from tl_ninjarmm.models.get_device_global_custom_fields_default_response_inner_content import GetDeviceGlobalCustomFieldsDefaultResponseInnerContent
from typing import Optional, Set
from typing_extensions import Self

class GetTicketAttributesDefaultResponseInner(BaseModel):
    """
    GetTicketAttributesDefaultResponseInner
    """ # noqa: E501
    id: Optional[StrictInt] = None
    attribute_type: Optional[StrictStr] = Field(default=None, alias="attributeType")
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    customize_for_end_user: Optional[StrictBool] = Field(default=None, alias="customizeForEndUser")
    name_for_end_user: Optional[StrictStr] = Field(default=None, alias="nameForEndUser")
    description_for_end_user: Optional[StrictStr] = Field(default=None, alias="descriptionForEndUser")
    end_user_option: Optional[StrictStr] = Field(default=None, alias="endUserOption")
    technician_option: Optional[StrictStr] = Field(default=None, alias="technicianOption")
    content: Optional[GetDeviceGlobalCustomFieldsDefaultResponseInnerContent] = None
    system: Optional[StrictBool] = None
    active: Optional[StrictBool] = None
    create_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="createTime")
    update_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="updateTime")
    __properties: ClassVar[List[str]] = ["id", "attributeType", "name", "description", "customizeForEndUser", "nameForEndUser", "descriptionForEndUser", "endUserOption", "technicianOption", "content", "system", "active", "createTime", "updateTime"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetTicketAttributesDefaultResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of content
        if self.content:
            _dict['content'] = self.content.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetTicketAttributesDefaultResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "attributeType": obj.get("attributeType"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "customizeForEndUser": obj.get("customizeForEndUser"),
            "nameForEndUser": obj.get("nameForEndUser"),
            "descriptionForEndUser": obj.get("descriptionForEndUser"),
            "endUserOption": obj.get("endUserOption"),
            "technicianOption": obj.get("technicianOption"),
            "content": GetDeviceGlobalCustomFieldsDefaultResponseInnerContent.from_dict(obj["content"]) if obj.get("content") is not None else None,
            "system": obj.get("system"),
            "active": obj.get("active"),
            "createTime": obj.get("createTime"),
            "updateTime": obj.get("updateTime")
        })
        return _obj


