# coding: utf-8

"""
    NinjaOne Public API 2.0

    Ninja One Public API documentation. <br><br> See also: <br>  <a href=\"https://resources.ninjarmm.com/API/Ninja+RMM+Public+API+v2.0.5+Device+Filter+Syntax.pdf\">Device Filter syntax</a><br> <a href=\"https://resources.ninjarmm.com/API/Ninja+RMM+Public+API+v2.0.5+Webhooks.pdf\">Webhooks</a>

    The version of the OpenAPI document: 2.0.9-draft
    Contact: api@ninjarmm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GetDeviceDiskDrivesDefaultResponseInner(BaseModel):
    """
    GetDeviceDiskDrivesDefaultResponseInner
    """ # noqa: E501
    bytes_per_sector: Optional[StrictInt] = Field(default=None, description="Number of bytes per sector", alias="bytesPerSector")
    description: Optional[StrictStr] = Field(default=None, description="Description")
    interface_type: Optional[StrictStr] = Field(default=None, description="Interface type", alias="interfaceType")
    manufacturer: Optional[StrictStr] = Field(default=None, description="Manufacturer")
    media_type: Optional[StrictStr] = Field(default=None, description="Media Type", alias="mediaType")
    model: Optional[StrictStr] = Field(default=None, description="Model")
    name: Optional[StrictStr] = Field(default=None, description="Name")
    partition_count: Optional[StrictInt] = Field(default=None, description="Number of partitions", alias="partitionCount")
    serial_number: Optional[StrictStr] = Field(default=None, description="Serial number", alias="serialNumber")
    size: Optional[StrictInt] = Field(default=None, description="Size (Bytes)")
    smart_capable: Optional[StrictBool] = Field(default=None, description="Is S.M.A.R.T. capable?", alias="smartCapable")
    status: Optional[StrictStr] = Field(default=None, description="Status")
    __properties: ClassVar[List[str]] = ["bytesPerSector", "description", "interfaceType", "manufacturer", "mediaType", "model", "name", "partitionCount", "serialNumber", "size", "smartCapable", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetDeviceDiskDrivesDefaultResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetDeviceDiskDrivesDefaultResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bytesPerSector": obj.get("bytesPerSector"),
            "description": obj.get("description"),
            "interfaceType": obj.get("interfaceType"),
            "manufacturer": obj.get("manufacturer"),
            "mediaType": obj.get("mediaType"),
            "model": obj.get("model"),
            "name": obj.get("name"),
            "partitionCount": obj.get("partitionCount"),
            "serialNumber": obj.get("serialNumber"),
            "size": obj.get("size"),
            "smartCapable": obj.get("smartCapable"),
            "status": obj.get("status")
        })
        return _obj


