# coding: utf-8

"""
    NinjaOne Public API 2.0

    Ninja One Public API documentation. <br><br> See also: <br>  <a href=\"https://resources.ninjarmm.com/API/Ninja+RMM+Public+API+v2.0.5+Device+Filter+Syntax.pdf\">Device Filter syntax</a><br> <a href=\"https://resources.ninjarmm.com/API/Ninja+RMM+Public+API+v2.0.5+Webhooks.pdf\">Webhooks</a>

    The version of the OpenAPI document: 2.0.9-draft
    Contact: api@ninjarmm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class MergeItamTagsPublicApiRequest(BaseModel):
    """
    MergeItamTagsPublicApiRequest
    """ # noqa: E501
    tag_ids: Optional[List[StrictInt]] = Field(default=None, description="Array of tag ids to merge", alias="tagIds")
    merge_method: Optional[StrictStr] = Field(default=None, description="Method to use - merge into an existing tag or create a new one", alias="mergeMethod")
    merge_into_tag_id: Optional[StrictInt] = Field(default=None, description="If merging into an existing tag, you must provide the target tag id here", alias="mergeIntoTagId")
    name: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=40)]] = Field(default=None, description="If creating a new tag, you must supply the new tag name here")
    description: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=250)]] = Field(default=None, description="If creating a new tag, you can supply the new tag description here")
    __properties: ClassVar[List[str]] = ["tagIds", "mergeMethod", "mergeIntoTagId", "name", "description"]

    @field_validator('merge_method')
    def merge_method_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['MERGE_INTO_EXISTING_TAG', 'MERGE_INTO_NEW_TAG']):
            raise ValueError("must be one of enum values ('MERGE_INTO_EXISTING_TAG', 'MERGE_INTO_NEW_TAG')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MergeItamTagsPublicApiRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if merge_into_tag_id (nullable) is None
        # and model_fields_set contains the field
        if self.merge_into_tag_id is None and "merge_into_tag_id" in self.model_fields_set:
            _dict['mergeIntoTagId'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MergeItamTagsPublicApiRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tagIds": obj.get("tagIds"),
            "mergeMethod": obj.get("mergeMethod"),
            "mergeIntoTagId": obj.get("mergeIntoTagId"),
            "name": obj.get("name"),
            "description": obj.get("description")
        })
        return _obj


