# coding: utf-8

"""
    NinjaOne Public API 2.0

    Ninja One Public API documentation. <br><br> See also: <br>  <a href=\"https://resources.ninjarmm.com/API/Ninja+RMM+Public+API+v2.0.5+Device+Filter+Syntax.pdf\">Device Filter syntax</a><br> <a href=\"https://resources.ninjarmm.com/API/Ninja+RMM+Public+API+v2.0.5+Webhooks.pdf\">Webhooks</a>

    The version of the OpenAPI document: 2.0.9-draft
    Contact: api@ninjarmm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class PolicyConditionCustomField(BaseModel):
    """
    Policy condition custom field
    """ # noqa: E501
    field_name: Annotated[str, Field(min_length=0, strict=True, max_length=250)] = Field(description="Custom field name", alias="fieldName")
    operator: StrictStr = Field(description="Custom field operator")
    value: Annotated[str, Field(min_length=0, strict=True, max_length=65535)] = Field(description="Custom field value")
    __properties: ClassVar[List[str]] = ["fieldName", "operator", "value"]

    @field_validator('operator')
    def operator_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['EQUALS', 'NOT_EQUALS', 'LESS_THAN', 'LESS_OR_EQUAL_THAN', 'GREATER_THAN', 'GREATER_OR_EQUAL_THAN', 'IS_NOT_NULL', 'CONTAINS', 'CONTAINS_NONE', 'CONTAINS_ANY']):
            raise ValueError("must be one of enum values ('EQUALS', 'NOT_EQUALS', 'LESS_THAN', 'LESS_OR_EQUAL_THAN', 'GREATER_THAN', 'GREATER_OR_EQUAL_THAN', 'IS_NOT_NULL', 'CONTAINS', 'CONTAINS_NONE', 'CONTAINS_ANY')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PolicyConditionCustomField from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PolicyConditionCustomField from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fieldName": obj.get("fieldName"),
            "operator": obj.get("operator"),
            "value": obj.get("value")
        })
        return _obj


