# coding: utf-8

"""
NinjaOne Public API 2.0

NinjaOne Public API documentation.

The version of the OpenAPI document: 2.0.9-draft
Contact: api@ninjarmm.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from tl_ninjarmm.models.device import Device
from tl_ninjarmm.models.maintenance import Maintenance
from tl_ninjarmm.models.node_references import NodeReferences
from tl_ninjarmm.models.note import Note
from typing import Set
from typing_extensions import Self


class VMGuest(Device):
    """
    VMGuest
    """  # noqa: E501

    files: Optional[StrictStr] = Field(default=None, description="Guest VM Files")
    full_name: Optional[StrictStr] = Field(
        default=None, description="Full Name", alias="fullName"
    )
    last_boot_time: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, description="Last VM Boot Time", alias="lastBootTime"
    )
    memory_size: Optional[StrictInt] = Field(
        default=None, description="VM Memory size (bytes)", alias="memorySize"
    )
    cores_per_socket: Optional[StrictInt] = Field(
        default=None, description="Number of Cores per Socket", alias="coresPerSocket"
    )
    cpu_cores: Optional[StrictInt] = Field(
        default=None, description="Total Number of CPU Cores", alias="cpuCores"
    )
    power_state: Optional[StrictStr] = Field(
        default=None, description="Current power state", alias="powerState"
    )
    tools_install_type: Optional[StrictStr] = Field(
        default=None,
        description="Guest tools installation type",
        alias="toolsInstallType",
    )
    tool_status: Optional[StrictStr] = Field(
        default=None, description="Guest tools status", alias="toolStatus"
    )
    tools_version: Optional[StrictStr] = Field(
        default=None, description="Guest tools version", alias="toolsVersion"
    )
    guest_os_full_name: Optional[StrictStr] = Field(
        default=None, description="Guest OS full name", alias="guestOSFullName"
    )
    guest_os_family: Optional[StrictStr] = Field(
        default=None, description="Guest OS family", alias="guestOSFamily"
    )
    guest_osid: Optional[StrictStr] = Field(
        default=None, description="Guest OS identifier", alias="guestOSId"
    )
    tools_version_status: Optional[StrictStr] = Field(
        default=None,
        description="Guest tools version status",
        alias="toolsVersionStatus",
    )
    snapshot_count: Optional[StrictInt] = Field(
        default=None, description="Number of snapshots", alias="snapshotCount"
    )
    snapshot_total_size: Optional[StrictInt] = Field(
        default=None,
        description="Total snapshot size (bytes)",
        alias="snapshotTotalSize",
    )
    __properties: ClassVar[List[str]] = [
        "id",
        "parentDeviceId",
        "organizationId",
        "locationId",
        "nodeClass",
        "nodeRoleId",
        "rolePolicyId",
        "policyId",
        "approvalStatus",
        "offline",
        "displayName",
        "systemName",
        "dnsName",
        "netbiosName",
        "created",
        "lastContact",
        "lastUpdate",
        "userData",
        "tags",
        "fields",
        "maintenance",
        "references",
        "ipAddresses",
        "macAddresses",
        "publicIP",
        "notes",
        "deviceType",
        "files",
        "fullName",
        "lastBootTime",
        "memorySize",
        "coresPerSocket",
        "cpuCores",
        "powerState",
        "toolsInstallType",
        "toolStatus",
        "toolsVersion",
        "guestOSFullName",
        "guestOSFamily",
        "guestOSId",
        "toolsVersionStatus",
        "snapshotCount",
        "snapshotTotalSize",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VMGuest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of maintenance
        if self.maintenance:
            _dict["maintenance"] = self.maintenance.to_dict()
        # override the default output from pydantic by calling `to_dict()` of references
        if self.references:
            _dict["references"] = self.references.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in notes (list)
        _items = []
        if self.notes:
            for _item_notes in self.notes:
                if _item_notes:
                    _items.append(_item_notes.to_dict())
            _dict["notes"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VMGuest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "parentDeviceId": obj.get("parentDeviceId"),
                "organizationId": obj.get("organizationId"),
                "locationId": obj.get("locationId"),
                "nodeClass": obj.get("nodeClass"),
                "nodeRoleId": obj.get("nodeRoleId"),
                "rolePolicyId": obj.get("rolePolicyId"),
                "policyId": obj.get("policyId"),
                "approvalStatus": obj.get("approvalStatus"),
                "offline": obj.get("offline"),
                "displayName": obj.get("displayName"),
                "systemName": obj.get("systemName"),
                "dnsName": obj.get("dnsName"),
                "netbiosName": obj.get("netbiosName"),
                "created": obj.get("created"),
                "lastContact": obj.get("lastContact"),
                "lastUpdate": obj.get("lastUpdate"),
                "userData": obj.get("userData"),
                "tags": obj.get("tags"),
                "fields": obj.get("fields"),
                "maintenance": Maintenance.from_dict(obj["maintenance"])
                if obj.get("maintenance") is not None
                else None,
                "references": NodeReferences.from_dict(obj["references"])
                if obj.get("references") is not None
                else None,
                "ipAddresses": obj.get("ipAddresses"),
                "macAddresses": obj.get("macAddresses"),
                "publicIP": obj.get("publicIP"),
                "notes": [Note.from_dict(_item) for _item in obj["notes"]]
                if obj.get("notes") is not None
                else None,
                "deviceType": obj.get("deviceType"),
                "files": obj.get("files"),
                "fullName": obj.get("fullName"),
                "lastBootTime": obj.get("lastBootTime"),
                "memorySize": obj.get("memorySize"),
                "coresPerSocket": obj.get("coresPerSocket"),
                "cpuCores": obj.get("cpuCores"),
                "powerState": obj.get("powerState"),
                "toolsInstallType": obj.get("toolsInstallType"),
                "toolStatus": obj.get("toolStatus"),
                "toolsVersion": obj.get("toolsVersion"),
                "guestOSFullName": obj.get("guestOSFullName"),
                "guestOSFamily": obj.get("guestOSFamily"),
                "guestOSId": obj.get("guestOSId"),
                "toolsVersionStatus": obj.get("toolsVersionStatus"),
                "snapshotCount": obj.get("snapshotCount"),
                "snapshotTotalSize": obj.get("snapshotTotalSize"),
            }
        )
        return _obj
